### ISSUE TITLE
3D Vector input

### ISSUE THREAD

**Issue by gsimone** [cocopon/tweakpane#102]
Hey! As you know we started using tweakpane a lot with react-three-fiber & threejs, so it's coming up that a vector3 type input would be extremely useful. I'll add some of my ideas:

- we could use the xy input and add a slider for z underneath like the RGB/color picker
![image](https://user-images.githubusercontent.com/1862172/98443378-2f7cd880-210b-11eb-86cc-e5a82ac63902.png)

- we could let the user choose any pair of xyz axes to manipulate with the Pad - not sure about the UI here. This would more easily allow for any vector dimension

**Comment by cocopon** [comment]
I'm also not sure about the dedicated UI but it's possible to add three input fields for Vector3. Is this enough for the first implementation?

**Comment by cocopon** [comment]
Added in #148. Please wait for the next release...
