### ISSUE TITLE
tweapane is not displayed if created with container option

### ISSUE THREAD

**Issue by robertoranon** [cocopon/tweakpane#107]
Hi,

   I found that if I create a tweakpane with the option 'container', it is not displayed. I verified that the value of the container is an actual div element.

Thanks for help,

Roberto

**Comment by cocopon** [comment]
It may be caused by your environment because the [official document](https://cocopon.github.io/tweakpane/) also uses `container` option and it works fine.

Can you share a minimum reproduction code like this?
https://codepen.io/cocopon/pen/jOMEdNe

**Comment by robertoranon** [comment]
Sorry if I did not reply earlier. Yes, you're right, a problem in my code caused the issue.
