### ISSUE TITLE
Disable keyboard shortcuts

### ISSUE THREAD

**Issue by felixfaire** [cocopon/tweakpane#108]
is there a way to disable keyboard shortcuts for inputs, for example the space bar will toggle the last selected check box / folder etc.

This isn't an 'issue' per-se but it is leading to some undesired behaviour which it would be good to be able to disable.

Thanks

**Comment by daryl-cecile** [comment]
Ideally, keyboard shortcuts should be kept as it keeps the component accessible to keyboard users. If absolutely necessary maybe an override option could be implemented, but this should really be given more thought - is it important enough to warrant making the component inaccessible to keyboard-primary users?

**Comment by cocopon** [comment]
I do not recommend to disable the default behavior in consistency reason. It may reduce usability. But if you still want to do that, maybe you can do that by listening keyboard events of the target element and preventing the default behavior.
