### ISSUE TITLE
Failed importing tweakpane to vite projects

### ISSUE THREAD

**Issue by SIGUSR97** [cocopon/tweakpane#112]
# Problem
I was trying to use tweakpane on an existing vite project demo, but importing it somehow fail does not work properly. To make sure that I didn't mess anything up in my own project I opened brand new poject `tweakpane-test` to see if the problem was reproducible with the following command:
```bash
mkdir tweakpane-test
yarn create @vitejs/app tweakpane-test --template vanilla
cd tweakpane-test
yarn
yarn add tweakpane
```
main.js
```javascript
import * as Tweakpane from "tweakpane";
console.log(Tweakpane);
```
what seems to be imported was an empty module as follows: 
![image](https://user-images.githubusercontent.com/52692296/103621687-8ae30f80-4f70-11eb-936f-3dde26b94933.png)
The strange thing is however, when I tried to import tweakpane on an existing vue project, it worked pretty much as expected. So I'm suspecting that this is an issue exclusive to rollup or vite? This is quite an annoying problem, please fix.

**Comment by cocopon** [comment]
> This is quite an annoying problem, please fix.

You can also fix it by sending a pull request. This is an open source project.
