### ISSUE TITLE
Receive the previous value on change event

### ISSUE THREAD

**Issue by aarongeorge** [cocopon/tweakpane#115]
It would be helpful to add a second parameter to the `change` callback so that you receive the previous value.

Is anyone opposed to this?

E.g.

```javascript
const PARAMS = { index: 0 }

const pane = new Tweakpane()

pane.addInput(PARAMS, 'index', {
	step: 1,
	min: 0,
	max: 100
}).on('change', (newValue, previousValue) => {

	// If `index` was `0` and has been changed to `1`
	// `newValue` = 1
	// `previousValue` = 0
	console.log(newValue, previousValue)
})
```

**Comment by cocopon** [comment]
I think it would be useful in some situations but not suitable for general use. For example, previous values for [MouseEvent](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent) (`clientX`, `clientY`, etc.) may also be useful but has not been implemented.

We also have to consider the second argument. (ref: #110) Maybe some kind of `(ev: SomeTweakpaneEvent) => void` would be better for this case.

**Comment by cocopon** [comment]
FYI, you can do it with one simple function like this:

```js
const params = {
  foo: 50,
  bar: '#f00',
};

const pane = new Tweakpane();

// Create a handler that stores a previous value
function handlePrev(handler) {
  let prevValue = undefined;
  
  return (newValue) => {
    handler(newValue, prevValue);
    prevValue = newValue;
  };
}

pane.addInput(params, 'foo', {
  min: 0,
  max: 100,
  step: 1,
}).on('change', handlePrev((newValue, prevValue) => {
  console.log(`[foo] new: ${newValue}, prev: ${prevValue}`);
}));

pane.addInput(params, 'bar', {
  min: 0,
  max: 100,
  step: 1,
}).on('change', handlePrev((newValue, prevValue) => {
  console.log(`[bar] new: ${newValue}, prev: ${prevValue}`);
}));
```

**Comment by LeonardoRick** [comment]
I think knowing the previous value of each bind would be really useful to implement a "undo" logic!
