### ISSUE TITLE
[Enhancement] Add visible precision parameter for number inputs

### ISSUE THREAD

**Issue by Lutymane** [cocopon/tweakpane#119]
Hi,

I've faced an issue that the UI doesn't show more than 2 decimals while working with some very small numbers, so I believe it'd be super cool to add a new parameter (like `{ decimals }`) for inputs that would explicitly set the visible precision.

Currently I had to tweak some constants by myself in `getSuitableDecimalDigits`, so hopefully it's not hard to implement

Here's an example why it's important
![image](https://user-images.githubusercontent.com/22231294/106379892-15782c80-63c0-11eb-8b94-8d68105036ec.png)

Thanks

**Comment by cocopon** [comment]
Could you share some code examples? Tweakpane try to compute suitable digits with that function automatically.

**Comment by Lutymane** [comment]
Oh, I've taken a closer look and somehow I completely ignored `step` option, which actually forces the rendering of needed amount of decimal digits, sorry 😅 Now everything works as intended
