### ISSUE TITLE
double callback on change of color pane

### ISSUE THREAD

**Issue by robertoranon** [cocopon/tweakpane#120]
Hi,

  I've noticed that, using a pane with a color input, the callback on the color change by the user is called two times per color change.

You can see the issue here: https://jsfiddle.net/robertoranon/zkwr7upt/

Thanks for help!

**Comment by cocopon** [comment]
Thank you for reporting the issue. It seems that only S-V pad and H slider has this problem and text inputs work fine.

**Comment by cocopon** [comment]
In addition, keyboard input fires a single event correctly and pointer input fires multiple events.

**Comment by robertoranon** [comment]
Yes, text input works fine as well as selection between options. However, I see the problem also on the RGB pane, not just HSV (see my previously linked jsfiddle)

**Comment by cocopon** [comment]
Fixed in e9acfa3. Thank you for reporting the issue and please wait for the next release.

**Comment by cocopon** [comment]
In addition, I have to add E2E testing to simulate mouse events. (jsdom doesn't have a support of it)
