### ISSUE TITLE
Feature request: delete Folder or element from pane

### ISSUE THREAD

**Issue by ieskudero** [cocopon/tweakpane#130]
It would be nice to have the ability to delete a folder or an element to update the pane dinamically. My use case is that depending of the selection of some checkboxes the pane elements ( or even folders) should change dinamically. 

I think it would be a great feture to be able to change the current pane without reseting it.

**Comment by cocopon** [comment]
You can use `.dispose()` of the component:
https://cocopon.github.io/tweakpane/api/classes/api_input_binding.inputbindingapi.html#dispose
https://cocopon.github.io/tweakpane/api/classes/api_folder.folderapi.html#dispose

**Comment by ieskudero** [comment]
Great!! I didn't know I could dispose individual elements. By the way, maybe the main page should be updated with this info. I checked folder and tips (for dispose) pages looking for this info:
https://cocopon.github.io/tweakpane/ui-components.html#folder
https://cocopon.github.io/tweakpane/misc.html#tips

And in neither of them shows that you could dispose individual elements.

Anyway, thanks for the info!!
