### ISSUE TITLE
Hidden not working on v 1.6.0

### ISSUE THREAD

**Issue by ciknowles** [cocopon/tweakpane#157]
Hi,

I've just upgraded to v 1.6.0 and *I think* the 'hidden' property doesn't appear to work.

After setting 'hidden' the html contains
`<div class="tp-lblv tp-v-hidden">...`

The css contains
`.tp-v .tp-v-hidden {
	display: none
}`

So the input is not hidden? Either the input needs the .tp-v class or the css needs additional rules?

Chris

**Comment by cocopon** [comment]
Thank you for reporting the issue. Fixed the problem and just released the latest version 1.6.1.
https://github.com/cocopon/tweakpane/releases/tag/1.6.1

**Comment by ciknowles** [comment]
Thanks - you are great, so quick.

Tested, issue fixed!

Chris
