### ISSUE TITLE
Allow to tweak input numeric values with mouse click + drag

### ISSUE THREAD

**Issue by vlucendo** [cocopon/tweakpane#185]
First off, great job with the library! It has replaced dat.gui as my creative coding ui :D

One of the nice features of dat was the ability to change the values of the input boxes just by clicking and dragging up / down. This is extremely helpful when tweaking any sort of visual effect where the range is unknown or when tweaking vector positions. It also provides a much more direct visual feedback.

Would be possible to have an option to allow this functionality?

Cheers!

**Comment by cocopon** [comment]
Thank you for using Tweakpane!

> just by clicking and dragging up / down

I have seen this kind of feature in other application but their direction is not up /down but to the left / right. I think horizontal dragging is more natural and confortable for the human arm. What do you think?

**Comment by vlucendo** [comment]
> I think horizontal dragging is more natural and comfortable for the human arm. What do you think?

Agree, horizontal also works better on multi-monitor setups compared to vertical where the space you have to move is often limited by the screen height.

**Comment by cocopon** [comment]
WIP
https://twitter.com/cocopon/status/1369978964077285385?s=20

https://user-images.githubusercontent.com/602961/110783261-89550100-82ab-11eb-988e-eda45f418654.mp4

**Comment by vlucendo** [comment]
That looks nice :)

**Comment by cocopon** [comment]
Released in 2.1.0!
