### ISSUE TITLE
Add Point 4D support

### ISSUE THREAD

**Issue by vlucendo** [cocopon/tweakpane#186]
I saw that recently the 3D vector input (Point 3D, #102) support was added and was wondering if it could be possible to add "Point 4D" support too.

WebGL libraries usually have this class (https://threejs.org/docs/index.html#api/en/math/Vector4) and it is very handy and common when passing variables to shaders or to tweak unnormalized quaternion rotations.

It would be very nice to have it the same way as Point 3D (1 extra text input field).

Cheers!

**Comment by cocopon** [comment]
Implemented in #195. Please wait for the next release.

![localhost_8080_input html](https://user-images.githubusercontent.com/602961/111020100-bf5ac800-8406-11eb-8890-1fcd3c4d745a.png)
