### ISSUE TITLE
先生、npm i したいです...

### ISSUE THREAD

**Issue by AtuyL** [cocopon/tweakpane#2]

**Comment by cocopon** [comment]
Done! Now you can install Tweakpane by `npm install tweakpane`.

**Comment by AtuyL** [comment]
ありがとうございます！助かります！
利用状況ですが、CSSはgulpを用いてパス指定でクローンしています。< 4ef4eef

**Comment by cocopon** [comment]
0.1.3では、SCSSおよび生成済みのCSSをパッケージに含めていまして、それぞれ `package.json` の `style` / `sass` で相対パスが取得できるようになっています。

--

From 0.1.3, the package contains SCSS files and compiled CSS, and you can get their relative path by `style` / `sass` key in `package.json`.
