### ISSUE TITLE
Import Tweakpane with NPM but no bundler

### ISSUE THREAD

**Issue by bolinocroustibat** [cocopon/tweakpane#207]
I would like to import Tweakpane in my module, after having added it with NPM, but without using any bundler.

When I do:
```
import Tweakpane from "./node_modules/tweakpane/dist/tweakpane.js";
pane = new Tweakpane();
```

I get the following:
`Uncaught SyntaxError: The requested module './node_modules/tweakpane/dist/tweakpane.js' does not provide an export named 'Tweakpane'`

Is there a way to do so?

**Comment by cocopon** [comment]
Could you tell me your environment (OS, Node.js, browser, etc.) and steps (how to set up a repository, install Tweakpane, and execute it, etc.) to reproduce the issue?

**Comment by bolinocroustibat** [comment]
Sure, sorry.
MacOS 11.2
Node.js v15.3.0
Browser Chrome

**Comment by bolinocroustibat** [comment]
Sure, sorry.
MacOS 11.2
Node.js v15.3.0
Browser Chrome

I install Tweakpane with npm (`npm install tweakpane`) but I don't use any bundler.

**Comment by cocopon** [comment]
Thank you for details! Tweakpane doesn't support ES module (`type="module"`) yet. So, at this point, you have to use the file without `import` feature, or use some CDN that have a feature to convert classic packages into ES modules (e.g. https://www.skypack.dev/).

**Comment by bolinocroustibat** [comment]
Thanks, will do. In the meantime, should I create an GitHub feature request issue to support ES module?

**Comment by cocopon** [comment]
It would be helpful, thank you!

**Comment by cocopon** [comment]
#209
