### ISSUE TITLE
[Plugin question] how to teardown listener or timer in plugin, if tweakpane is been removed

### ISSUE THREAD

**Issue by hirohe** [cocopon/tweakpane#208]
thanks for the tweakpane plugin system, i'm try to write some extensions

if i using `setTimeout` in plugin for debounce purpose.

than i need to call `clearTimeout` if tweakpane removed. but i don't know if there has `destroy` or `depose` callback for plugin

**Comment by cocopon** [comment]
Great, you may be a first plugin developer (except me)!

>  i don't know if there has destroy or depose callback for plugin

Ah, I missed that functionality. I'll add it in the next release so please wait.

**Comment by cocopon** [comment]
Added support for `onDispose()` of a controller and a view. Please refer the latest diff of the template:
https://github.com/cocopon/tweakpane-plugin-template/commit/1da991608b4d9dd4222f1225e263d2a5a2f93687

**Comment by cocopon** [comment]
oops, I have to implement recursive disposing of container (e.g. folder) items... trying to fix it.

**Comment by cocopon** [comment]
Fixed the issue, and now `pane.dispose()` triggers disposing sub items correctly. Please try the latest version 2.1.6.
