### ISSUE TITLE
disable on .on('change'  on refresh

### ISSUE THREAD

**Issue by robertoranon** [cocopon/tweakpane#289]
Hi,

   sometimes I need to change a value in the tweak pane gui from code, as a result of some internal change, using the `refresh` method, but I don't want to fire the 'change' event, which I do however need when it is the user who changes the value. Is kind of behavior possible?

Thanks a lot!

**Comment by cocopon** [comment]
If the value is changed, `change` event should be fired. this behavior is by design.

You can do that by using a flag like this:

```js
let refreshing = false;

pane.on('change', () => {
  // Skip if refreshing
  if (refreshing) { return; }

  ...
});

...

refreshing = true;
pane.refresh();
refreshing = false;
```

**Comment by cocopon** [comment]
Any updates? @robertoranon

**Comment by robertoranon** [comment]
Sorry, I was a little busy ... I understand, thanks!
