### ISSUE TITLE
Improve performance for hidden elements

### ISSUE THREAD

**Issue by vlucendo** [cocopon/tweakpane#315]
Hello,

Thanks for the great work on the library!

I've noticed recently that when I have a big pane with multiple folders and inputs, the performance of the page is not great. After some tests I found that with all the folders closed the performance was still bad, like so:

![bandicam 2021-05-14 05-24-37-592](https://user-images.githubusercontent.com/11018451/118217164-32b79f00-b475-11eb-8332-ea3535629461.jpg)

Then what I tried was to set`display: none` on the invisible elements of the minified folders, and the performance dramatically improved with no loss of functionality:

![bandicam 2021-05-14 05-25-02-758](https://user-images.githubusercontent.com/11018451/118217245-58dd3f00-b475-11eb-977f-59a2681ae66e.jpg)

Would be possible to set `display: none` on hidden folder elements and `display: block` when they are shown/maximized to improve the rendering performance?

Cheers!

**Comment by cocopon** [comment]
Thank you for reporting the issue.

- What is the performance that the image represents? e.g. clicking a element, adding a element, etc.
- Could you share an example code and steps? I'd like to reproduce the problem in my environment to fix the issue.

**Comment by vlucendo** [comment]
Hello,

- The images are a request animation frame on the performance tab of chrome dev tools. The orange bar is the same in both (some javascript running on every frame, not related to tweakpane), the purple bars are `Hit test` and `Update Layer Tree` tasks. They are computed on every frame and get pretty expensive when there's a big tweakpane with many different folders / inputs, even if tweakpane is not being interacted with.

- A way to reproduce it could be to create a folder, add lots of elements to it (1000 Point 4Ds for example) and collapse that folder. You'll notice that now there's a significant update layer time added to every frame. The way to fix this would be to set `display: none` to the `tp-brkv` element of folders when they are collapsed.

This issue becomes problematic when for example you are doing a webgl website and control some of its elements with tweakpane.  This additional time required on every frame can make the webgl jank and skip frames, especially on not very powerful hardware.

Thanks!

**Comment by cocopon** [comment]
Thank you! I'll look into it.

**Comment by cocopon** [comment]
Fixed in #319. Thank you for reporting the issue and please wait for the next release!
