### ISSUE TITLE
Typings problem with '@tweakpane/core'

### ISSUE THREAD

**Issue by Lutymane** [cocopon/tweakpane#321]
Hi,

I'm using tweakpane in typescript and I've just updated to 3.0 and got a problem 
`Property 'addTab' does not exist on type 'Pane'`. 

Investigating further I've found out that there's a problem with '@tweakpane/core'
`Cannot find module '@tweakpane/core' or its corresponding type declarations`, 
so it fails to import 'FolderApi' and basically everything, which causes typescript errors. It seems this module declarations are missing.

**Comment by cocopon** [comment]
Does installing `@tweakpane/core` solve the problem?

**Comment by cocopon** [comment]
Could you share more information about your environment? (e.g. OS, Node.js, project configurations like: package.json, tsconfig.json, etc.)

**Comment by Lutymane** [comment]
Oh, I didn't know '@tweakpane/core' is an actual package O_O 
Adding that one did fix the issue as expected, thanks!

Do you consider adding type declarations from that package to the main one, though?
Like `declare module '@tweakpane/core' {...}` and etc

**Comment by cocopon** [comment]
> Do you consider adding type declarations from that package to the main one, though?

It may be possible, but I think non-standard things will always cause distortion and reduce maintainability. So for now, please install the core library if you want to use its type definitions.

**Comment by cocopon** [comment]
Updated the document:
https://cocopon.github.io/tweakpane/getting-started.html

**Comment by Lutymane** [comment]
Nice! Would it be more clear to specify it as `--save-dev` though? Since we need only typings from there?

**Comment by cocopon** [comment]
You're right! Fixed the flag in the document.
