### ISSUE TITLE
`format` not supported on `addMonitor` ?

### ISSUE THREAD

**Issue by photonstorm** [cocopon/tweakpane#327]
Thanks for this great lib :)

I've got several `addMonitor`s running, which work great, but they're showing decimals places for what are integer values. So I tried `format: (v: number) => Math.trunc(v)` but it appears to just be ignored. The same format works fine on `addInput`, however, so is this just a limitation of `addMonitor` ?

**Comment by cocopon** [comment]
Thank you for using Tweakpane. And yes, it should be added. I'll implement it later.

**Comment by cocopon** [comment]
Implemented in #329. Please wait for the next release.

**Comment by photonstorm** [comment]
Great, thanks :)
