### ISSUE TITLE
Problem with event.last 

### ISSUE THREAD

**Issue by vujadin** [cocopon/tweakpane#337]
When using 'range' input it works correctly when slider component is used (by setting event.last = true only on pointerUp event). However, if input field is used it fires event.last = true on every change, for example when user holds arrowUp key to increase value, on every step event.last is true. In this situation event.last should be true only when user releases arrowUp key. Also, DOM blur event should be used if user manually sets value of input to dispatch event with last = true.

![image](https://user-images.githubusercontent.com/4639385/126484927-c903c024-c2b3-4181-9cae-5cf673e930c2.png)
firing event with last = true on every change while arrow up key is pressed

**Comment by cocopon** [comment]
Fixed in #339. Please wait for the next release.

**Comment by indus** [comment]
Will this fix also work for the range slider of the essentials plugin?

**Comment by cocopon** [comment]
I need to update the plugin with a new core to fix the bug. Please wait...

**Comment by cocopon** [comment]
@indus Released in [0.1.1](https://github.com/tweakpane/plugin-essentials/releases/tag/0.1.1).
