### ISSUE TITLE
Adding option for random value

### ISSUE THREAD

**Issue by perymimon** [cocopon/tweakpane#341]
Can you add the option to regenerate random values depends on the input constrain 

like: 
```
const pane = new Pane(parameters, {
    title: 'Galaxy Generator',
});
....

pane.random()

const input = new pane.addInput(....)
input.random()

const folder =  pane.addFolder( {...})
folder.random()
....

**Comment by cocopon** [comment]
Tweakpane cannot know a suitable value candidate for each property, so I think it's out of scope of the library.
