### ISSUE TITLE
Image input

### ISSUE THREAD

**Issue by metehus** [cocopon/tweakpane#343]
Is Image Input on the roadmap? It would be an awesome resource to use for changing textures, sprites, etc. It could be done with a file input and also via drag-and-drop. The result could be a HTMLImageElement content.

**Comment by cocopon** [comment]
I'm interested in this feature because `HTMLImageElement` is part of HTML standard.

At the moment, you can implement it yourself using the [plugin system](https://cocopon.github.io/tweakpane/plugins.html), or use existing [third-party plugin](https://github.com/ayamflow/tweakpane-image-plugin) (I haven't tried yet).

**Comment by metehus** [comment]
> I'm interested in this feature because `HTMLImageElement` is part of HTML standard.
> 
> At the moment, you can implement it yourself using the [plugin system](https://cocopon.github.io/tweakpane/plugins.html), or use existing [third-party plugin](https://github.com/ayamflow/tweakpane-image-plugin) (I haven't tried yet).

Just found about plugins and about this one. It has some things missing so i think i'm gonna fork that

**Comment by metehus** [comment]
Also, one thing that I want to do is to accept URLs on the drop area in order to receive images from external places. For that, i would need to do HTTP requests, involving async stuff. Do you know a good way to do that on the current structure of plugins?

**Comment by cocopon** [comment]
Tweakpane adopts traditional MVC architecture. You can listen for view events and send a HTTP request by a controller.

**Comment by metehus** [comment]
I have decided to turn this into [a plugin](https://github.com/metehus/tweakpane-image-plugin). Thanks for the help!

**Comment by cocopon** [comment]
Great work! Thank you for sharing it.
