### ISSUE TITLE
[TS] Use "keyof" for typing of binding property

### ISSUE THREAD

**Issue by Lutymane** [cocopon/tweakpane#348]
Hi, 

It'd like to propose an enhancement. It'd be great to use `keyof` in methods like `addInput`, `addMonitor`, etc for typing the binding property.

Currently the typing is the following:
`addInput<O extends Record<string, any>, Key extends string>(object: O, key: Key, opt_params?: InputParams): InputBindingApi<unknown, O[Key]>`

So instead of `Key extends string` use `Key extends keyof O`, so we could also have a nice autocompletion as well as more safety without mistyping names.

![Code_-_Insiders_HgamR3bFDT](https://user-images.githubusercontent.com/22231294/133634224-e95ce0a5-590d-4ec7-818f-52a561405bc6.png)

**Comment by cocopon** [comment]
Thank you for the great idea! Applied in #349.

**Comment by cocopon** [comment]
Released in 3.0.6. Thank you for your help!
