### ISSUE TITLE
Serialization option when exporting presets

### ISSUE THREAD

**Issue by metehus** [cocopon/tweakpane#350]
Recently, I forked a made plugin and made some [changes to it](https://github.com/metehus/tweakpane-image-plugin).

I was trying to make a system to export the pane on a JSON in order to import it again later. Unfortunately, the plugin saves the internal value as an HTMLImageElement, making it impossible to serialize into a JSON:
![image](https://user-images.githubusercontent.com/22124518/135264146-d991e49b-1fb7-41e3-9f85-8fc8ea3f7a49.png)

It would be great to have something like a `exportValue(value: In): PrimiviteValue` to convert the internal saved value to a primitive value that can be put in a json field

**Comment by cocopon** [comment]
The preset will be replaced with the "blade state" in the next major version v4:
https://github.com/cocopon/tweakpane/issues/431#issuecomment-1459071158

After considering, I think serialization option is still out of scope of the library and it should be handled outside pane.

In the new preset system, you can detect a custom blade by adding a special field, and it means you can make the preset value serializable by post-processing.
