### ISSUE TITLE
Possibility of using 'passive' event handlers?

### ISSUE THREAD

**Issue by Lutymane** [cocopon/tweakpane#357]
Add passive flag to touch events and etc., so Chrome doesn't get mad about it in console.

![chrome_ZYhnLzom5E](https://user-images.githubusercontent.com/22231294/141022212-f54a69be-d8e1-47e2-b2ac-3fd847e11b68.png)

**Comment by cocopon** [comment]
I cannot find these messages with the [official document](https://cocopon.github.io/tweakpane/) and the latest Chrome. Is there any additional conditions to show them?

**Comment by Lutymane** [comment]
The official document generates these warnings as well on Chrome 95.0.4638.69.

Do you perhaps have warnings disabled in the console?

**Comment by cocopon** [comment]
Hmm... I can only see this warning (maybe not related to Tweakpane).

![image](https://user-images.githubusercontent.com/602961/141674209-0092ed89-53bd-4465-bb33-5d856d628ef1.png)

Log level is `Default` that includes `Warnings`:
![image](https://user-images.githubusercontent.com/602961/141674259-9b5cb3e5-cc5e-472e-8d73-f7880966d315.png)

And here are my settings but I cannot find a related flag:
![image](https://user-images.githubusercontent.com/602961/141674250-d8f13718-c058-4d9a-8f03-e0f3e41758e7.png)

**Comment by Lutymane** [comment]
Do you have the console open while reloading the page? Because it won't show the warning if you open the console after page (re)loads (as the event listener will already be registered)

**Comment by Lutymane** [comment]
Ah, I found the problem, haha. You need to enable "Verbose" in logging, as it's not included in the "Default" preset

**Comment by cocopon** [comment]
Thanks! Now I can see the message. I'll dig into the issue...

**Comment by cocopon** [comment]
Fixed in #358! Thank you for reporting the issue!

**Comment by cocopon** [comment]
Also released in 3.0.6!
