### ISSUE TITLE
ButtonAPI.on returns void instead of this

### ISSUE THREAD

**Issue by Zyie** [cocopon/tweakpane#36]
Hey, the `ButtonAPI.on` function returns `void` instead of `ButtonAPI` which is different from all the others.

```
this.box = pane.addInput(this, 'test').on('change', () =>
{
   // do something
});

this.button = pane.addButton();
this.button.on('click', () =>
{
    // do something
});
```

**Comment by cocopon** [comment]
Thank you for reporting the issue! Fixed in the latest version 1.3.2.
