### ISSUE TITLE
Dynamically change the InputParams of an Input?

### ISSUE THREAD

**Issue by pgaxatte** [cocopon/tweakpane#360]
Hello,

Is there any way to dynamically change the parameters of an input?

In my case I'd like to be able to the set the max value of an input (let's call it INPUT1) to the value of another input (INPUT2).

I don't see any way to access the InputParams after creation.

Should I dispose of INPUT1 and recreate it with the new max set to the value of INPUT2 when it changes?

**Comment by cocopon** [comment]
> Should I dispose of INPUT1 and recreate it with the new max set to the value of INPUT2 when it changes?

Right, this is the standard way to do so.

But you really don't want to dispose it, you can do it with an unsafe way (not recommended):
https://codesandbox.io/s/objective-tu-t1lm6?file=/src/index.ts

```ts
import { SliderTextController } from "@tweakpane/core";
import { Pane } from "tweakpane";

const PARAMS = {
  foobar: 0,
  minFoobar: 0
};

const pane = new Pane();
const input = pane.addInput(PARAMS, "foobar", {
  min: 0,
  max: 100
});

pane
  .addInput(PARAMS, "minFoobar", {
    min: 0,
    max: 50
  })
  .on("change", (ev) => {
    const min = ev.value;

    // It works but is unsafe (not recommended)
    const stc = input.controller_.valueController as SliderTextController;
    const sc = stc.sliderController;
    sc.props.set("minValue", min);

    // Tweakpane limits the input range, but not the value itself
    // it has to be updated manually
    if (PARAMS.foobar < min) {
      PARAMS.foobar = min;
      pane.refresh();
    }
  });
```

**Comment by cocopon** [comment]
Feel free to reopen the issue if you still have the problem.
