### ISSUE TITLE
Change or read options after object creation

### ISSUE THREAD

**Issue by dinther** [cocopon/tweakpane#371]
Sorry, this is really a support question but I don't know where else to post.
Given the following code: 
```
ppsMonitor = settingsPane.addMonitor(laserSimulator, 'ppsActual', {view: 'graph', min: 0, 100, interval: 1000});     
```

Is there anywhere information how I can change the "max" property in the above example?
This is such a great looking UI. It makes web programming fun. Documentation and examples are a bit light.

I just have no idea how to navigate these UI objects in code. I tried digging through
```
ppsMonitor.controller_
ppsMonitor.emitter_
```
The only thing that makes sense is ppsMonitor.label :-)

https://user-images.githubusercontent.com/1192916/146966898-ef1783bc-ec07-4a9b-b74d-5898ffb6acab.mp4

**Comment by cocopon** [comment]
Added changes in #404, and you'll be able to change min/max value in the next version like this:

```js
const pane = new Tweakpane.Pane();
const m = pane.addMonitor(params, 'foo', {
  view: 'graph',
  min: 0,
  max: 100,
});

m.controller_.valueController.props_.set('minValue', 40);
m.controller_.valueController.props_.set('maxValue', 60);
```

These are still private fields and may change in future updates. Please be careful.

**Comment by loganzartman** [comment]
for anyone who is trying to automatically set the range of their graph, as of 3.1.6 you can access the array of values in the graph via

```js
m.controller_.valueController.value_.value_
```

and, for the FPS graph specifically, you can set `minValue` and `maxValue` via

```js
m.controller_.valueController.graphC_.props_.set
```
