### ISSUE TITLE
description panel 

### ISSUE THREAD

**Issue by rexmalebka** [cocopon/tweakpane#372]
Hello

is there a way to create a "description" panel, for example for a help section or credit section

I was thinking on addMonitor with strings, but I think it's not the right way to solve it.

**Comment by cocopon** [comment]
Hello. There is no way to create such a component. You can use a text monitor as you said, but this is not the intended use.

You can also create your own description component with the plugin system:
https://cocopon.github.io/tweakpane/plugins.html
