### ISSUE TITLE
FeatureRequest: class property 

### ISSUE THREAD

**Issue by indus** [cocopon/tweakpane#375]
Would be nice to be able to provide a property `class` or `klass` that gets added to the blade element. This would allow to easily style only specific inputs or add icons to their labels with `:before` and similar stuff.

**Comment by Lutymane** [comment]
It is quite easy to style individual blades and inputs already, though

You can access DOM elements from blades and inputs:
`Blade.controller_.view`
which gives access to three elements, so you may apply classes to them
```
{
  element,
  labelElement,
  valueElement
}
```

![chrome_rm6RY0GPyY](https://user-images.githubusercontent.com/22231294/160110623-c65152e6-68d4-426a-8a70-e044bc25db22.png)

You may check the demo
https://codepen.io/lutman/pen/BaJpgVJ

**Comment by indus** [comment]
Thats what I do right now as well. I just thought for convenience. But I totally undestand if you don't want to bloat the options; and using what is there already is propably gives the biggest flexibility. I'm closing this.
