### ISSUE TITLE
joystick view  

### ISSUE THREAD

**Issue by djmisterjon** [cocopon/tweakpane#378]
this thing are really nice ! 
I replace my old datGui with this one !

Am also looking for a kind of joystick view 
![image](https://raw.githubusercontent.com/loopmode/react-nipple/master/packages/react-nipple/preview.gif)]
or coords dots slider , based on position and pivot.
![image](https://user-images.githubusercontent.com/24865815/159518509-4c5d858b-2374-4d04-a821-0b6812a0b2c8.png)

did you have one already ?

**Comment by Lutymane** [comment]
Is this what you're probably looking for?
https://cocopon.github.io/tweakpane/input-bindings.html#point
