### ISSUE TITLE
type error 

### ISSUE THREAD

**Issue by djmisterjon** [cocopon/tweakpane#379]
**buttongrid** seem not support event.
![image](https://user-images.githubusercontent.com/24865815/160023572-519f8af6-02b0-4335-82fb-79b65557bfc9.png)

ex:
```ts
		pane.addBlade( {
			label: 'moveTo',
			view: 'buttongrid',
			size: [ 3, 3 ],
			cells: ( x:number, y:number ) => ( {
				title: [
					[ 'NW', 'N', 'NE' ],
					[ 'W', '*', 'E' ],
					[ 'SW', 'S', 'SE' ],
				][y][x],
			} ),
		} ).on( 'click', ( v ) => $.transform.position.set( ( $._sceneW / 2 ) * v.index[0], ( $._sceneH / 2 ) * v.index[1] ) );
	} )( $Camera );
```

**Comment by cocopon** [comment]
That is by design. BladeApi interface doesn't have a method `on`, cast it to the specific API.

Ref: https://github.com/cocopon/tweakpane/issues/355#issuecomment-950285742

BTW, the repository of Button Grid is here:
https://github.com/tweakpane/plugin-essentials
