### ISSUE TITLE
Disable or declare programmatically input type

### ISSUE THREAD

**Issue by lavolpecheprogramma** [cocopon/tweakpane#38]
Hi,
Is it possible to disable an input type or declare programmatically it?
For example, I don't want to use point2D for an object that contains x and y properties but I want to use the slider to change these values.

Thank you very much for your works. It is very useful!

**Comment by cocopon** [comment]
Thank you for using Tweakpane! How about adding each properties to the pane directly?

```js
const params = {
  foo: 'bar',
  somePoint: {x: 12, y: 34},
};

const pane = new Tweakpane();
pane.addInput(params.somePoint, 'x', {min: -100, max: 100});
pane.addInput(params.somePoint, 'y', {min: -100, max: 100});
```

**Comment by lavolpecheprogramma** [comment]
yes, it can be a simple solution! thank you for your support ^
