### ISSUE TITLE
add custom dom classes or id ?

### ISSUE THREAD

**Issue by djmisterjon** [cocopon/tweakpane#382]
hi, its possible to add custom classes name or id to a folder or a pane ?
Am trying to update my old vanilla gui design with tweakpane, but i cant find in doc, how pass custom clsname or id to reproduce some design i had with my older panel.
![a3fga3vacaf](https://user-images.githubusercontent.com/24865815/160291023-1f1a7420-9ea3-464c-bcdd-0a3bd09232e2.gif)

**Comment by Lutymane** [comment]
https://github.com/cocopon/tweakpane/issues/375

Similar for folders, they have following element references
```
// buttonElement
// titleElement
// containerElement
// element
```
