### ISSUE TITLE
Question: conditional rendering

### ISSUE THREAD

**Issue by afternoon2** [cocopon/tweakpane#388]
Hello! I'd like to ask if there is a possibility to conditionally render (and rerender) the Pane's or folder's content depending on the input's value? For example:

```js
const ui = new Pane({
    title: 'ettings',
    expanded: true,
    container: document.getElementById('tweakpane-container'),
  });

const control = ui.addInput({ 'Param': 'Value A' }, 'Param' {
  options: {
    'Value A': 'Value A',
    'Value B': 'Value B'
   },
 });

const optionsFolder = ui.addFolder({
  title: 'Options',
});

control.on('change', ev => {
  // possible input removal API?
  optionsFolder.removeInputs();
  switch (ev.value) {
    case 'Value A':
      // add set of inputs for 'Value A' type
      break;
    case 'Value B':
    default:
      // add set of inputs for 'Value B' type
    break;
  }
})
```

**Comment by cocopon** [comment]
You can use `optionsFolder.remove()` or `optionsFolder.children[n].dispose()` to remove inputs. See API reference for details:

https://cocopon.github.io/tweakpane/api/classes/index.folderapi.html

**Comment by afternoon2** [comment]
oh dear, my apologies, I totally didn't notice it (neither my VSCode Typescript plugin did!) 🤦
