### ISSUE TITLE
.refresh() doesn't refresh blade list

### ISSUE THREAD

**Issue by SilverGaucho** [cocopon/tweakpane#389]
Hei there!

It seems that the refresh method of a pane doesn't refresh correctly the value of a blade list.
All the other components work correctly when refreshed

Here is my code:
```
      scope.LINE_PARAMS = {
             
              MarkerOrientation: 'end',        
             
        };
        scope.linePane = new Tweakpane.Pane();        
        scope.linePane.addBlade({view: 'list',label: 'Line Cap',options: 
                                [{text: 'none', value: 'none'},
                                {text: 'start', value: 'start'},
                                {text: 'end', value: 'end'},],
                                value: scope.LINE_PARAMS.MarkerOrientation})
                        .on('change', (ev) => {  console.log(ev.value); });

        //In function refresh:
        function refresh(props){
             
                        Object.assign(scope.LINE_PARAMS,props); 
              
                        scope.linePane.refresh();
                        scope.linePane.hidden = false;
         }
```

Many thanks and compliments with this awesome work!

**Comment by cocopon** [comment]
`refresh()` updates all *bindings*, not blades.
https://cocopon.github.io/tweakpane/api/classes/blade_root_api_root.rootapi.html#refresh

How about using bindings to synchronize parameter values with input values?

**Comment by SilverGaucho** [comment]
@cocopon ur right, but my problem is that parameters comes from a foreign object. I solved disposing and recreating the pane. Probably is not the best solution but it works without significant performance degradation. Thanks
