### ISSUE TITLE
export presets using folders

### ISSUE THREAD

**Issue by charlieroberts** [cocopon/tweakpane#39]
It seems like folders should be included in preset export. This would help remove the need for hacks like `presetKey`. For example, given two folders `obj1` and `obj2` an exported preset might look like:

```js
{
  obj1: {
    x:0,
    y:0,
    z:0
  },
  obj2: {
    x:1,
    y:1,
    z:0
  }
}
```

**Comment by cocopon** [comment]
`Preset` is not the current state of pane but a set of bound values. So currently I don't have a plan to apply view hierarchy to the preset.
