### ISSUE TITLE
refresh should update slider constraints

### ISSUE THREAD

**Issue by tomorrowevening** [cocopon/tweakpane#390]
```
const myPane = myGUI.addInput(settings, 'time', {
  disabled: true,
  min: 0,
  max: 2,
  step: 0.01,
  label: 'Time'
});

const bounds = myPane.controller_.binding.value as BoundValue
const constraint = bounds.constraint_ as CompositeConstraint
const range = constraint.constraints[1] as RangeConstraint
range.maxValue = 1
myPane.refresh()
```

You'll notice the slider can only move halfway there, because the new max is half the old one

**Comment by cocopon** [comment]
Fields that has a name ended with `_` are private. It's not supported and doesn't work properly in some cases.

Currently, disposing the input and re-creating it with new options is the way to update the slider range.

**Comment by tomorrowevening** [comment]
Ah okay, thanks!
