### ISSUE TITLE
Is it possible to add tooltips to any control?

### ISSUE THREAD

**Issue by miltoncandelero** [cocopon/tweakpane#391]
I am making a UI and it would be nice to get a tooltip when you hover certain buttons or inputs.

I think this would be a cool feature to add

Thanks a lot for your awesome work!

**Comment by cocopon** [comment]
Here is the answer:

```js
const pane = new Pane();

const b1 = pane.addInput({input: "text"}, "input");
const e1 = b1.controller_.view.element;
e1.querySelector('input').title = 'tooltip 1';

const b2 = pane.addButton({title: 'Button'});
const e2 = b2.controller_.view.element;
e2.querySelector('button').title = 'tooltip 2';
```

But it uses a private field... should be made public, I'll create a issue about this problem.

**Comment by cocopon** [comment]
Added `element` field in #400. Please wait for the next release.
