### ISSUE TITLE
Breaking changes in v4

### ISSUE THREAD

**Issue by cocopon** [cocopon/tweakpane#396]
WIP
https://github.com/cocopon/tweakpane/tree/v4

- [x] Publish beta package
- [x] CSS injection for plugin bundle
- [x] Organize exports ([Node.js v20.1.0 documentation](https://nodejs.org/docs/latest-v20.x/api/packages.html))
- [x] #209
- [x] Update documents
  - [x] Preset
  - [x] Migration from v3 to v4
  - [x] API reference
  - [x] Update plugins: essentials and camerakit
- [x] Re-check `TODO:` list
- [x] Some minor refactoring
  - [x] Replace `TpEvent.key` with `TpEvent.target.key`
  - [x] Fix broken layout of the folder when the title is empty
- [x] #431, #509
- [x] #486
- [x] #381
- [x] #480
- [x] #450 
- [x] #455 
- [x] #466
- [x] #481
- [x] #485
- [x] #510
- [x] Delete `@deprecated` functions

**Comment by cocopon** [comment]
# Migration guide: for plugin developers
- Migrate your package to ES modules
  - Upgrade `rollup.config.js`
  - Add `.js` postfix to all import statements
- `LabeledValueController` -> `LabeledValueBladeController`
- `parseParams` -> `parseRecord`
- `ParamsParser` -> `MicroParser`
- `LabelController` drops `blade` field
  - Implement an own blade controller if your plugin directly uses `LabelController`

**Comment by cocopon** [comment]
Released [4.0.0-alpha.0](https://www.npmjs.com/package/tweakpane/v/4.0.0-alpha.0). Checking plugins' compatibility...

**Comment by kitschpatrol** [comment]
I know this is closed, but in case it's helpful to anyone else I've ported a bunch of community plugins to Tweakpane 4.

I have PRs open on all of the original repos, but if anyone needs a Tweakpane 4 compatible plugin right away, the forks are on NPM:

[@kitschpatrol/tweakpane-image-plugin](https://www.npmjs.com/package/@kitschpatrol/tweakpane-image-plugin)
[@kitschpatrol/tweakpane-plugin-profiler](https://www.npmjs.com/package/@kitschpatrol/tweakpane-plugin-profiler)
[@kitschpatrol/tweakpane-plugin-rotation](https://www.npmjs.com/package/@kitschpatrol/tweakpane-plugin-rotation)
[@kitschpatrol/tweakpane-plugin-thumbnail-list](https://www.npmjs.com/package/@kitschpatrol/tweakpane-plugin-thumbnail-list)
[@kitschpatrol/tweakpane-plugin-waveform](https://www.npmjs.com/package/@kitschpatrol/tweakpane-plugin-waveform)
[@kitschpatrol/tweakpane-textarea-plugin](https://www.npmjs.com/package/@kitschpatrol/tweakpane-textarea-plugin)
