### ISSUE TITLE
Odd number sequence

### ISSUE THREAD

**Issue by jereroy** [cocopon/tweakpane#399]
Hi!

I would like to add an input to my panel that can have an odd sequence, for example : [3, 5, 7, 9 , 11, ...]. Right now i'm using : 

```
 f.addInput(this.params, 'foo',
  {   
    min: 1,
    max : 15,
    step: 2
  }).on('change', (size) => {
    // this.params.foo = size.value + 1;
  });
```
which does't work because my value get rounded. As you can see, I tried incrementing it with the "change" event. I get the right value, but the UI is not updated. I also tried using the refresh function, but as I modify the value with the "change" event, it does not work.

Is there a clean way to do this?

**Comment by cocopon** [comment]
Here is an example to do that:

```js
import { Pane } from 'tweakpane';

const pane = new Pane();
const params = {
  param: 3,
};
pane
  .addInput(params, 'param', {
    format: (v) => v.toFixed(0),
    min: 1,
    max: 15,
  })
  .on('change', (ev) => {
    params.param = Math.floor(ev.value / 2) * 2 + 1;
    pane.refresh();
  });
```

Anyway I think that the step value should respect its min value. I'll fix it later.

**Comment by cocopon** [comment]
Added changes in #401. Please wait for the next release.
