### ISSUE TITLE
Insert input/monitor in a specific order

### ISSUE THREAD

**Issue by abolfazlshirazi** [cocopon/tweakpane#40]
Hi,
It will be great to have an option for adding input/monitor in the pane/folder in a specific order, not at the end of all elements.
Currently, when adding items with for example ".addInput()" or ".addButton()", the item will be placed at the end of the pane. How if it is possible to place an item in a specific index in the pane? The reason is, after creating the pane, in some applications, it may be necessary to delete (dispose()) some of the elements and substitute them with some new inputs, so it is required to place the item exactly on the position it was deleted, not at the end of the pane.

**Comment by cocopon** [comment]
Just released 1.3.3 and now you can specify `index` option.

```js
const pane = new Tweakpane();
pane.addButton({title: 'Run'});
pane.addButton({title: 'Stop'});
pane.addButton({
  index: 1,
  title: '**Reset**',
});
```
