### ISSUE TITLE
declarative definitions + bidirectional reactivity

### ISSUE THREAD

**Issue by Enteleform** [cocopon/tweakpane#408]
Hey there 🙂. Just found this lib recently and was hooked immediately. The UI implementation is super clean, the API + docs are thorough & easy to work with, and it's very well executed overall. 💯/10

I just spun up a creative coding sketchbook with `solid-start`, `solid-command-palette`, `p5` and `tweakpane` over the last few days. I made a demo / code-walkthrough of it for a software development opportunity I'm considering, figured I'd post it here as well to demonstrate some functionality that might be useful for future versions of Tweakpane or perhaps an extension library. I'm curious to hear your thoughts about them.
&nbsp;  

Here's the demo video:

<a href="https://www.youtube.com/watch?v=1gc5bRq4fCM">
  <img src="https://i.imgur.com/LPNKShl.png" width=400px/>
</a>

&nbsp;  
It starts off with a quick explanation of the use case that was a catalyst for the implementations, and then a few quick notes about a PR I made for `solid-command-palette`.

The Tweakpane-specific content starts at about `2:07` in case you want to skip the other stuff.

There's also some focus on type-manipulation for a bit in the middle. The super condensed version would be:
```yaml
- Declarative Definitions:   2:07  - 5:36
- Bidirectional Reactivity:  10:13 - 13:18
```

**Comment by cocopon** [comment]
Thank you for the information. I think this feature is out of scope of the library because currently there is no native way to observe property changes except using a timer.
