### ISSUE TITLE
Folder status: expanded or not 

### ISSUE THREAD

**Issue by Dvisik** [cocopon/tweakpane#410]
How I can get the status of each folder of my pane? 
I need to know expanded or not. Function _onchange_ does't work with folders

**Comment by cocopon** [comment]
You can use `expanded` property of the folder. See the API document for details: 
https://cocopon.github.io/tweakpane/api/classes/index.folderapi.html#expanded

```js
const pane = new Pane();
const f = pane.addFolder({ title: 'folder' });
f.addButton({ title: 'button' });

f.on('fold', () => {
  console.log(f.expanded);
});
```

**Comment by Dvisik** [comment]
Works! Thanks!
