### ISSUE TITLE
Monitor with Interval filling heap memory

### ISSUE THREAD

**Issue by Jor-ban** [cocopon/tweakpane#415]
Is there any methods to stop interval on monitor rather than setting a timer by myself and calling update manually?
![image](https://user-images.githubusercontent.com/51119083/174909992-0d6bf1e8-f242-489e-8ba5-d0bbe111f080.png)
this is heap before page close
![image](https://user-images.githubusercontent.com/51119083/174910056-2aff2542-a2a1-4f86-85ed-c257ee2ed802.png)
this is when I open page again
Before those monitors everything worked fine (without memory leak)

**Comment by cocopon** [comment]
How about passing `interval: 0` to the monitor:
https://cocopon.github.io/tweakpane/monitor-bindings.html#interval

**Comment by Jor-ban** [comment]
> How about passing `interval: 0` to the monitor

In this case graphs are just not rendered, timeout works still, so it doesn't fix my problem
I've tried to dispose them, but, it doesn't remove interval

**Comment by Jor-ban** [comment]
![image](https://user-images.githubusercontent.com/51119083/174927947-b492c5ee-a475-470d-b36a-80d29a5053fa.png)
I guess It won't be such easy :)

**Comment by cocopon** [comment]
Hmm it's strange, BladeApi has a setter for `disabled`:
https://cocopon.github.io/tweakpane/api/classes/index.monitorbindingapi.html#disabled

It works fine for me so may be caused by your environment:
https://codesandbox.io/s/tweakpane-sandbox-forked-18hong?file=/src/index.js

**Comment by Jor-ban** [comment]
Oh thank you for help, I guess you are right, and its caused by environment
