### ISSUE TITLE
Container width exception caused by using `new Pane({ container: document.getElementById("xxx") })`

### ISSUE THREAD

**Issue by wangrongding** [cocopon/tweakpane#416]
recurring address: 👇
https://codesandbox.io/s/interesting-bogdan-xivfo2?file=/src/App.vue  

![image](https://user-images.githubusercontent.com/42437658/175033032-f7a0f78e-1bf2-4dcd-bbec-9284e70223c3.png)

**Comment by wangrongding** [comment]
How can the width of the controller remain so wide?

**Comment by cocopon** [comment]
Feel free to reopen the issue if you have any updates.

**Comment by wangrongding** [comment]
thank's💗
