### ISSUE TITLE
Support for signals

### ISSUE THREAD

**Issue by pspeter3** [cocopon/tweakpane#425]
I just saw Preact released a signals library that is UI independent. The signals are basically an object with a value property. I was wondering what the best way would be to connect them to Tweakpane?

**Comment by cocopon** [comment]
I'm not a Preact user, but if it is just an object with a `value` property, is there any problem with `pane.addInput(signal, 'value')` ? More concrete problem or example codes can be useful for the discussion.

**Comment by pspeter3** [comment]
You're totally right. I thought that this wouldn't work with the proxies but it passing the signal as the first property works great. The only thing is to remember to pass the `label` property as well. Thank you so much!
