### ISSUE TITLE
List blade change event

### ISSUE THREAD

**Issue by FractalHQ** [cocopon/tweakpane#427]
Hey there!  I'm hoping to run some custom logic based on the selected item in a list, but it appears there is no change event for it.  Is there a workaround for this or another approach I'm overlooking?

**Comment by FractalHQ** [comment]
solved it!
```js
optionBlade.element.addEventListener('change', (e) => {
		console.log(optionBlade.value)
})
```

**Comment by FractalHQ** [comment]
It seems typescript doesn't like it though

![Screenshot 2022-09-12 at 11 01 59 AM](https://user-images.githubusercontent.com/55504972/189688207-59b64960-f62c-4df1-ab9e-4219f151231c.png)

**Comment by cocopon** [comment]
You have to cast `BladeApi` to specific type of the blade API. `pane.addBlade()` returns a generic type for a technical reason.

**Comment by FractalHQ** [comment]
In case anyone else is confused, I sorted it out by doing this:

```ts
const selectedAnimation = folder.addBlade({
	view: 'list',
	label: 'scene',
	options: [
		{ text: 'wormhole', value: 'wormhole' },
		{ text: 'field', value: 'field' },
		{ text: 'staircase', value: 'staircase' },
	],
	value: p.activeAnimation,
}) as ListApi<'wormhole' | 'field' | 'staircase'>
```

**Comment by FractalHQ** [comment]
Could this be fixed internally with `infer` or a conditional type?

**Comment by cocopon** [comment]
Does "fix" mean that `addBlade()` returns an appropriate concrete type for passed params, right?

**Comment by FractalHQ** [comment]
yea that's what I was thinking might be ideal

**Comment by cocopon** [comment]
It may be difficult because an output will be changed dynamically with registered plugins.

For example, the code below returns `SliderApi` by default:

```
const b = pane.addBlade({
  view: 'slider',
  min: 0,
  max: 1,
  value: 0.5,
});

console.log(b instanceof SliderApi);  // true
```

But after registering a plugin that provides a blade for `{view: 'slider}`, the return value will be different.

**Comment by FractalHQ** [comment]
Ah ok, yea that complicates things.  Perhaps a simpler solution could be to add an example to the documentation?

Because I was still confused when you said:
> You have to cast BladeApi to specific type of the blade API.

And it took me awhile to figure out how to do it correctly.  A simple example like this for typescript users might be nice:
```ts
type FooBar = 'foo' | 'bar'

const select = pane.addBlade({
  view: 'list',
  value: 'foo',
  label: 'FooBar',
  options: [
    { text: 'foo', value: 'foo' },
    { text: 'bar', value: 'bar' },
  ],
}) as ListApi<FooBar> // select.on('change') will now be typed correctly
```

Maybe I'm just slow though 😅

**Comment by cocopon** [comment]
Added a section about casting a blade in #512:

![](https://user-images.githubusercontent.com/602961/224040143-abef7fec-0b51-49d9-a090-574bb95eda0f.png)
