### ISSUE TITLE
Are types broken?

### ISSUE THREAD

**Issue by fenomas** [cocopon/tweakpane#432]
Having just installed the newest version (3.1.0), I'm getting typescript warnings for all APIs in this library. For example:

```js
import { Pane } from 'tweakpane'
var pane = new Pane()
pane.addFolder()   // tsc warning: Property 'addFolder' does not exist on type 'Pane'.
```

And poking around `dist/types`, the files there seem to include only a small subset of the actual API. E.g. `/dist/types/pane/pane.d.ts` contains only 2-3 public methods.

**Comment by cocopon** [comment]
Have you installed the core package?

https://cocopon.github.io/tweakpane/getting-started/
<img width="871" alt="image" src="https://user-images.githubusercontent.com/602961/193732336-3d58b52e-8255-4d6f-94d7-3ce0579c7453.png">

**Comment by fenomas** [comment]
Ahhh thank you - I'm migrating from v1.x, and I didn't notice the import had changed!

**Comment by brandon-lb** [comment]
Wonderful project. I was confused here too. I installed it by selecting the `npm` icon from the readme and verifying the npm package name and noticed types were not working. Adding some install instructions on the readme and/or npm page might be helpful for some!

**Comment by cocopon** [comment]
Added some minor improvements to the docs (and it will be applied from the next release). Thank you for your feedback!
