### ISSUE TITLE
Folding a `Pane` causes other unrelated instances to move

### ISSUE THREAD

**Issue by FractalHQ** [cocopon/tweakpane#433]
It seems like all instances of `Pane` are reacting to the first pane's fold events?  Is there some way to avoid this?

Here is a demonstration:

![tp-bug](https://user-images.githubusercontent.com/55504972/194399819-c198f1e8-cd45-46e3-904d-3455417e3b00.gif)

**Comment by cocopon** [comment]
Can you share a minimal code to reproduce the issue? It seems that it is caused by the DOM structure.

**Comment by FractalHQ** [comment]
After adding some CSS it seems to have gone away, and I can't seem to recreate this now.  I'll make sure to make a reproduction and re-open this if I encounter it again!
