### ISSUE TITLE
What is the proper way to programatically change an input?

### ISSUE THREAD

**Issue by FredericoCoelhoNunes** [cocopon/tweakpane#434]
Hi all,

I have a button in my Pane that opens a dialog to choose a folder in my filesystem. I want the folder path to be stored in a text input, so that when the user presses save, this value is included in `pane.exportPreset()`

This is the way I managed to do it, by rummaging through the source code:
```
    ...
    const folder_location = pane.addInput(PARAMS, 'folder_location');

    const btn = pane.addButton({
        title: 'Select Folder',
    });
      
    btn.on('click', () => {
        (<this handles the dialog>).then(result => {
            folder_location.controller_.binding.value.rawValue = result
        });
    });
```

It feels like there is probably a more direct way to change the input value than `.controller_.binding...` but I couldn't figure it out. the `value` setter didn't work for me (`folder_location.value = ...`)

Any thought would be greatly appreciated. Thank you

**Comment by cocopon** [comment]
How about the code below:

```
btn.on('click', () => {
  (<this handles the dialog>).then(result => {
    PARAMS.folder_location = result;
    pane.refresh();
  });
});
```

**Comment by cocopon** [comment]
Feel free to reopen the issue if you have any updates.
