### ISSUE TITLE
Module support

### ISSUE THREAD

**Issue by jellehak** [cocopon/tweakpane#435]
Great library would be nice to have a module available.

So you can also use it without bundlers. Like so:
```html
<script type="importmap">
  {
    "imports": {
      "tweakpane": "https://cdn.jsdelivr.net/npm/tweakpane@3.1.0/dist/tweakpane.esm.js"
    }
  }
</script>
```

**Comment by cocopon** [comment]
Thank you for using Tweakpane, and it's duplicated with #209.
