### ISSUE TITLE
Unable to access all buttons in a folder by scrolling

### ISSUE THREAD

**Issue by pavank61295** [cocopon/tweakpane#436]
Hi Team,

I created a folder with 15 inputs and 8 buttons. when I exapand folder, bottom inputs are not in screen and unable to scrool down to access them. Attached snapshot of folder inputs.  
Could you help us on scrooling to access bottom inputs also.

Thanks
Pavan

![image](https://user-images.githubusercontent.com/109271734/196918139-0f6e96a3-8ca0-476c-a4e0-7cbca1515368.png)

**Comment by cocopon** [comment]
Tweakpane itself doesn't have a scrolling feature, so it seems to be a problem with your page. Please check the style of the container elements (e.g. `overflow`, `height`, etc.).

**Comment by cocopon** [comment]
Feel free to reopen the issue if you have any updates.
