### ISSUE TITLE
logarithmic/exponential sider

### ISSUE THREAD

**Issue by indus** [cocopon/tweakpane#438]
I'm trying to get a slider that has a exponential scaling. With the `format` option it is easy to do so for the slider itself:
```
pane.addInput({e:3}, 'e', {
  min:0, max:5,
  format:(val) => (10**val).toExponential(1)
})
```
But it will fail when the user puts a number like `1000` in the textfield as it gets clipped to min/max. Is there an option to intercept inputs to the text field to adjust the value before?

**Comment by cocopon** [comment]
`format` is for display text, not an actual value.

This issue may be helpful:
https://github.com/cocopon/tweakpane/issues/56#issue-629050493

**Comment by indus** [comment]
@cocopon hm - the linked example is not much help. I think it is from atime before the format option was implemented (?) and monkey-patches that functionality. Listening to the change event seems to late to adjust the value put into the text field. Is there some undocumented "oninput" event that can be overriden to adjust the input from the text-field?

**Comment by cocopon** [comment]
I don't have a plan to add an event like `oninput`. You can implement a logarithmic slider as a plugin. Here are some useful links:

Plugin template:
https://github.com/tweakpane/plugin-template

Tips for creating plugins:
https://github.com/cocopon/tweakpane/discussions/426

Built-in number plugin: https://github.com/cocopon/tweakpane/blob/d521d6b7224dc4d3d1981e131f495e0c8a29a8d0/packages/core/src/input-binding/number/plugin.ts

**Comment by indus** [comment]
I'm not sure I have the passion to maintain a plugin in the long run and adapt it quick enough to new versions. But I now have a monkey-patch that allows to pass the neccessary transform functions:

``` JS
const pane = new Tweakpane.Pane();

/* PATCH */

let inp_number = pane.pool_.pluginsMap_.inputs.find(inp => inp.id == 'input-number');

const { controller } = inp_number;

inp_number.controller = (_args) => {
	let c = controller(_args);
	if (c.textController && _args.params.format?.parser) {
		const parser = c.textController.parser_;
		c.textController.parser_ = (value) => _args.params.format.parser(parser(value));
	}
	return c;
};

//// uncomment to get transformed values in PARAMS
// const { reader, writer } = inp_number.binding;
// inp_number.binding.reader = _args => _args.params.format?.reader ? _args.params.format?.reader : reader(_args);
// inp_number.binding.writer = _args => _args.params.format?.writer ? _args.params.format?.writer : writer(_args);

/* USAGE */

let exp_formatter = (value) => (10 ** value).toExponential(1);
exp_formatter.parser = (value) => Math.log10(value);
//// uncomment to get transformed values in PARAMS
// exp_formatter.reader =  (value) => Math.log10(value);
// exp_formatter.writer =  (target, value) => target.write(10**value);

const PARAMS = { exp: 3 };
pane.addInput(PARAMS, 'exp', {
	format: exp_formatter,
	min: 0,
	max: 6
}).on('change', (evt) => {
	console.log(evt.value); // exponent if reader/writer is unpatched
});
```

This is not limited to exponential scaling. It may be usefull with tween function as well (ease-in, ease-out, ect. )...

**Comment by indus** [comment]
The monkey patch works for the range slider from the [Essentials-Plugin](https://github.com/tweakpane/plugin-essentials#interval) as well, but each input has to be patched seperatly:
``` JS
pane.registerPlugin(TweakpaneEssentialsPlugin);

/* PATCH */

pane.pool_.pluginsMap_.inputs
.filter(inp => ['input-number', 'input-interval'].includes(inp.id))
.forEach(inp => {
	const { controller } = inp;

	inp.controller = _args => {
		let c = controller(_args);
		if (c.textController && _args.params.format?.parser) {
			const parser = c.textController.parser_;
			c.textController.parser_ = (value) => _args.params.format.parser(parser(value));
		}
		return c;
	};

	//// uncomment to get transformed values in PARAMS
	// const { reader, writer } = inp.binding;
	//inp.binding.reader = _args => _args.params.format?.reader ? _args.params.format?.reader : reader(_args);
	//inp.binding.writer = _args => _args.params.format?.writer ? _args.params.format?.writer : writer(_args);
});
```
