### ISSUE TITLE
event when you change tab

### ISSUE THREAD

**Issue by rishipandey125** [cocopon/tweakpane#448]
is there any way to know if the user changed tabs on the pane?

**Comment by cocopon** [comment]
You can use `select` event like this:

```ts
import { Pane } from 'tweakpane';

const pane = new Pane();
const tab = pane.addTab({
  pages: [
    { title: 'foo' },
    { title: 'bar' },
  ],
});
tab.on('select', (ev) => {
  console.log(ev.index);
});
```

**Comment by rishipandey125** [comment]
wonderful! thank you so much!

**Comment by cocopon** [comment]
Upgraded the official document and it's now documented:
https://cocopon.github.io/tweakpane/api/interfaces/tweakpane._internal_.TabApiEvents.html#select
