### ISSUE TITLE
How to hide / show controllers?

### ISSUE THREAD

**Issue by antlii** [cocopon/tweakpane#476]
Hi,

Is there any way to show and hide controllers with simple functions like in dat.GUI (gui.show() and gui.hide()) to get similar behavior here?

Thanks!

**Comment by cocopon** [comment]
You can use `hidden` property:
https://cocopon.github.io/tweakpane/misc/#visibility

**Comment by antlii** [comment]
Oh man, I spent an hour and somehow failed to find this in the description.
My apologies and thanks for your time! 🙏
