### ISSUE TITLE
Adding HEX to Color component

### ISSUE THREAD

**Issue by antlii** [cocopon/tweakpane#482]
I was wondering if there is a chance to add a HEX value for the color model selection list in the Color component.

<img width="384" alt="image" src="https://user-images.githubusercontent.com/52974033/218797286-be205a09-0095-43fb-bdd9-9799c4767056.png">

The thing is that coders (like me ;) mostly work directly with RGB/HSL/HSV values, but users generally used HEX color codes. It would be very useful if it'll be possible to enter the HEX code into the picker, in that case.

Thanks! ❤️

**Comment by antlii** [comment]
Amazing, thanks for your support, Hiroki! ❤️

**Comment by cocopon** [comment]
Released in v4.0.0.
