### ISSUE TITLE
Manual way to change checkboxes, or when disabling checkboxes, set checkboxes to false/unchecked

### ISSUE THREAD

**Issue by wenxich** [cocopon/tweakpane#488]
I'm currently using a checkbox (A) which, when clicked, would "disable" a panel (B) of other checkboxes.

For this, it would be useful to be able to set all the checkboxes in panel B to false/unchecked when B is disabled. Right now, when I disable B, all the checkboxes in B stay checked. Thus, when B is re-enabled, I would have to manually uncheck the boxes for them to "reset".

My apologies if there's already a feature that does this somewhere that I've missed - I'd appreciate any help! (Also, let me know if this wasn't a clear enough explanation - I can provide further clarification or screenshots if needed).

**Comment by cocopon** [comment]
Thank you for using Tweakpane. How about using importing/exporting a preset to disable multiple checkboxes?

1. Get a preset via `exportPreset()`
2. Set all checkbox values of the preset to `false`
3. Apply changes by passing the modified preset to `importPreset()`

Document:
https://cocopon.github.io/tweakpane/misc/#imex

**Comment by cocopon** [comment]
Feel free to reopen the issue if you have any updates.

**Comment by wenxich** [comment]
> Thank you for using Tweakpane. How about using importing/exporting a preset to disable multiple checkboxes?
> 
> 1. Get a preset via `exportPreset()`
> 2. Set all checkbox values of the preset to `false`
> 3. Apply changes by passing the modified preset to `importPreset()`
> 
> Document: https://cocopon.github.io/tweakpane/misc/#imex

Hello @cocopon,

Thank you so much! This method worked for mostly everything - except for when I have 2 tabs in a pane, but they both have a checkbox titled "show", and the preset only exports one "show" and not the other. Is there possibly a workaround of this? I know the easy way out would be to rename one of them, but it would be preferable to keep them both as "show" for user understandability.

Thank you again! Let me know if you need further clarification also.

**Comment by cocopon** [comment]
You can use `presetKey` for the current version to specify a key for export: https://cocopon.github.io/tweakpane/misc/#imex

The next major version v4 will have another export mechanism and you don't have to specify such a key.
