### ISSUE TITLE
Height 0px for folders nested in tabs

### ISSUE THREAD

**Issue by antlii** [cocopon/tweakpane#496]
The problem is still here, but it happens with folders nested in tabs
https://codepen.io/antlii/pen/eYLzMQy

_Originally posted by @antlii in https://github.com/cocopon/tweakpane/issues/374#issuecomment-1442259044_

**Comment by cocopon** [comment]
Thank you for reporting the issue. 

It seems to be occurred when expanding a folder in an inactive tab. Inactive tab has the style `display: none`, and height computation will be failed in the hidden container.

**Comment by antlii** [comment]
@cocopon Thank you so much for maintaining the library! 🙏

**Comment by cocopon** [comment]
This should be fixed in the latest version 3.1.5. Thank you for reporting the issue.
