### ISSUE TITLE
[Feature request] Add `format` to PointDimensionParams

### ISSUE THREAD

**Issue by vnvyvu** [cocopon/tweakpane#511]
Can you add `format` to `Point 3D/4D` similar `Number`

https://github.com/cocopon/tweakpane/blob/c69ddc543845edc72f1f20a9ca4c8baf70218417/packages/core/src/common/params.ts#L13

I think it will be useful!

**Comment by cocopon** [comment]
Implemented in #515, and will be released in the next major version 4.

**Comment by cocopon** [comment]
Released in v4.0.0.
