### ISSUE TITLE
Missing types for addInput

### ISSUE THREAD

**Issue by myselfgroot** [cocopon/tweakpane#517]
typescript support for addInput is missing

<img width="580" alt="Screenshot 2023-03-12 at 12 08 36 AM" src="https://user-images.githubusercontent.com/39885973/224505931-0d37129f-8922-4811-bcc7-2cb292848e3a.png">
 
i guess the issue is in the package.json devDependencies check the version of `@tweakpane/core` it is showing .. 

because of this the the `@tweakpane/core` is not installed and getting the input error

You can check this in the npm attaching the screenshot for reference 

<img width="580" alt="Screenshot 2023-03-12 at 12 30 59 AM" src="https://user-images.githubusercontent.com/39885973/224506849-07b0eebe-76db-428d-80ec-0dde6e696e0e.png">

**Comment by cocopon** [comment]
This is intentional behavior.

https://cocopon.github.io/tweakpane/getting-started/
> $ npm install --save tweakpane
>
> \# Additional type definitions for development in TypeScript
> $ npm install --save-dev @tweakpane/core

TypeScript support is optional. It is completely unnecessary package for pure JavaScript users.

**Comment by myselfgroot** [comment]
Got it, Thanks for the quick response.

Closing the issue
