### ISSUE TITLE
Making a plugin full-width

### ISSUE THREAD

**Issue by Tresky** [cocopon/tweakpane#521]
I'd like to make a plugin for Tweakpane that allows you to have an expanded list that you can hover on and select an item from the list. Like the image below.

<img width="410" alt="Screen Shot 2023-03-16 at 4 04 25 PM" src="https://user-images.githubusercontent.com/3902022/225740109-00edce83-e461-4fbb-9463-0d1e91bd38e6.png">

From my experiments so far, it seems like any input binding produces a side-by-side view with a variable name on the left and an editable field on the right. Is there any way to accomplish something sort of like this?

**Comment by cocopon** [comment]
`label: null` option hides a label and widen a control area.

![image](https://user-images.githubusercontent.com/602961/225921971-017c8902-7de4-45e7-8b30-616581b0524c.png)

```js
const pane = new Pane();
pane.addInput({foo: 1}, 'foo', {min: 0, max: 1});
pane.addInput({foo: 1}, 'foo', {min: 0, max: 1, label: null});
```

(This option doesn't work properly due to a bug and has been fixed in the latest version 3.1.7)

**Comment by Tresky** [comment]
Awesome! That worked. Thanks! Is there a way to control this from inside the plugin? I couldn't find a way to force the label to null.

**Comment by cocopon** [comment]
There is no way to control it from the plugin. All bindings have a label and users expect to be able to specify the label.

**Comment by Tresky** [comment]
Okay I figured that would be the case as it would create unexpected behavior. Thanks for the help!

**Comment by cocopon** [comment]
FYI: You can create a blade without label not as an input binding, but as a blade without a binding. Built-in `separator` plugin may be helpful to know its structure:

https://github.com/cocopon/tweakpane/blob/03bbd12592534ec6af96a23cae130083d4f886bd/packages/core/src/blade/separator/plugin.ts

**Comment by Tresky** [comment]
I didn't realize that. Thank you! I'll look into this and go this route instead.
