### ISSUE TITLE
feature request: number input default should be whole integer

### ISSUE THREAD

**Issue by autonome** [cocopon/tweakpane#530]
Currently if I put 300000 in an input field for a milliseconds value, it renders as `300000.00` which is confusing to users.

It would be better to default to integers, unless the value is a fractional number.

**Comment by cocopon** [comment]
You can use the option `step: 1` for integer values, or use `format` specify the display format directly. Tweakpane has display format estimation, but it's difficult to know what is the expected digits for users.
