### ISSUE TITLE
folder.dispose() does not trigger pane 'change' event

### ISSUE THREAD

**Issue by autonome** [cocopon/tweakpane#533]
Example:

```
const pane = new Tweakpane.Pane();
pane.on('change', () => alert('change!'));
const folder = pane.addFolder();
folder.dispose();
```

Expected: change event fires
Actual: change event does not fire

**Comment by cocopon** [comment]
`change` event is for handling bound values, not a folder itself. Currently there is no way to detect disposing, but you can create a utility function for workaround like this:

```js
function wrapDispose(target, onDispose) {
  target.dispose();
  onDispose();
}
```

**Comment by autonome** [comment]
ok, thanks!
