### ISSUE TITLE
can't use panels with shadow-dom

### ISSUE THREAD

**Issue by b3008** [cocopon/tweakpane#535]
When nesting panels within the shadow dom of a custom element, tweakpane styling cannot be applied. Are there any ways to amend this?

**Comment by cocopon** [comment]
Can you share a minimal code to reproduce the issue? [CodeSandbox](https://codesandbox.io/) can be useful in this case.

**Comment by b3008** [comment]
Thank you for the response, here's an example:

https://codesandbox.io/s/tender-http-l583vl?file=/index.html

(for some reason I have to press `cmd+s` for the web-component to render after loading the sandbox)

**Comment by cocopon** [comment]
You can clone the default style element and place it into the shadow root.

```js
const styleElem = document.querySelector('style[data-tp-style="default"]');
this.root.appendChild(styleElem.cloneNode(true));
```

**Comment by cocopon** [comment]
Feel free to reopen the issue if you have any updates.

**Comment by b3008** [comment]
thank you for this solution
