### ISSUE TITLE
Inline color picker intercepts hover and clicks when collapsed

### ISSUE THREAD

**Issue by ccammack** [cocopon/tweakpane#538]
![2023-04-20 19_27_33-Tweakpane inline picker - Brave](https://user-images.githubusercontent.com/6925189/233527123-82e5314e-b4d4-4b00-bac8-e3532658f10d.png)
![2023-04-20 19_27_51-Tweakpane inline picker - Brave](https://user-images.githubusercontent.com/6925189/233527138-25648baf-d386-4eee-b3ab-7b5408c07fc1.png)
[Here's an example.](https://codepen.io/ccammack/pen/WNaogKa)

**Comment by cocopon** [comment]
Fixed in the latest version 3.1.9.
