### ISSUE TITLE
does has any plan for web component build by svelte?

### ISSUE THREAD

**Issue by yieryi** [cocopon/tweakpane#543]
hello, i have use dat.gui. when i see this tweakpane,i realize i will use it in many program project. meanwhile, the svelete which framework is friendly for make webcompoent,i use it too. as the title meaning , are you have any plane make this project to webcompoent by svelte?

**Comment by cocopon** [comment]
Hello, I don't have a plan to add such a dependency. "Dependency-free" is one of the concept of Tweakpane. https://github.com/cocopon/tweakpane#concept

**Comment by yieryi** [comment]
that's very cool, i see it, thank you
