### ISSUE TITLE
Issue with text selection on quick clicks in toggle box or space area

### ISSUE THREAD

**Issue by ZRNOF** [cocopon/tweakpane#545]
Hi,

I'm using Tweakpane library in my project, and I've noticed that there's an issue with quick clicks on the Tweakpane toggle box causing text selection. When I quickly click on the toggle box, sometimes the text gets selected.

![圖片](https://user-images.githubusercontent.com/89278589/234607936-da4d0578-9679-40b0-984f-c6f2d6316503.png)

I use preventDefault() to solve this.

Btw, Tweakpane is my fav gui that I've found. Thank you for your amazing work.

Thanks,
Zaron

**Comment by cocopon** [comment]
Fixed in #592. Thank you for reporting the issue.

**Comment by cocopon** [comment]
Released 4.0.3.
