### ISSUE TITLE
Hyperlink to v4 release notes results into a 404 error

### ISSUE THREAD

**Issue by NULLYUKI** [cocopon/tweakpane#556]
In the [migration guide](https://tweakpane.github.io/docs/migration/v4/) for the v4 beta, there is a hyperlink for the release notes.
![grafik](https://github.com/cocopon/tweakpane/assets/42326194/ff3c6755-a1b5-4d87-a20e-90dbc4a42150)
Clicking on this hyperlink, results into getting directed to the 404 Github error page.
![grafik](https://github.com/cocopon/tweakpane/assets/42326194/3d049dbc-9c61-418b-ab74-da934c50a646)
This is the URL from the hyperlink: https://github.com/cocopon/tweakpane/releases/tag/4.0.0

**Comment by cocopon** [comment]
Fixed.
