### ISSUE TITLE
Allow only numeric values for numeric sliders input areas

### ISSUE THREAD

**Issue by antlii** [cocopon/tweakpane#561]
Guys, is there any way to prevent non-numeric text in the slider's input areas?
It is supposed to be a place only for numbers, so maybe it makes sense to make such an improvement.

I keep running into this issue using hotkeys every time I forget to take the focus off a parameter field 😅

https://github.com/cocopon/tweakpane/assets/52974033/35a6b031-ea45-4014-84c2-cafec182c988

**Comment by cocopon** [comment]
It can be achieved by handling an input value directly, but not recommended for a usability perspective.

```js
const pane = new Tweakpane.Pane();
const params = {foo: 0};

const i = pane.addInput(params, 'foo', {min: 0, max: 1});
// Get an input element for the binding
const inputElem = i.controller_.valueController.view.element.querySelector('input');

// NOT RECOMMENDED from a usability perspective
inputElem.addEventListener('keyup', (ev) => {
  // Erase non-numeric chars
  inputElem.value = inputElem.value.replaceAll(/[^0-9\.e\+-]/g, '');
});
```

**Comment by antlii** [comment]
Thanks, Hiroki! ❤️
Well, it might be an option, for individual cases.
