### ISSUE TITLE
Update plugin-essentials to use new 4.x api

### ISSUE THREAD

**Issue by hzuo** [cocopon/tweakpane#568]
Post 4.0, the docs still point to plugin-essentials:
- https://github.com/cocopon/tweakpane/blob/8f51679f7a68bf596a43188d3cc8b05c38ba429b/packages/tweakpane/src/doc/template/plugins/index.html#L23
- https://github.com/cocopon/tweakpane/blob/8f51679f7a68bf596a43188d3cc8b05c38ba429b/packages/tweakpane/src/doc/template/plugins/dev/index.html#L22

But plugin-essentials has not been updated to use the new 4.0 plugin API.

If plugin-essentials is still supported, it should be updated to use the new plugin API.

Thanks!

**Comment by cocopon** [comment]
I forgot to bump up the version from beta... just published.
https://github.com/tweakpane/plugin-essentials/releases/tag/0.2.0

Thank you for letting me know!
