### ISSUE TITLE
Is there any hide/show functionality

### ISSUE THREAD

**Issue by ciknowles** [cocopon/tweakpane#57]
I really like your plugin. Used datgui and controlkit but this seems cleaner.

Is there any way to hide/show an element? For example I might make a selection that should then hide/show a number of other buttons/inputs?

**Comment by cocopon** [comment]
Thank you for using Tweakpane!

How about using a folder?
https://cocopon.github.io/tweakpane/misc.html#folder

You can show/hide child components by expanding/collapsing a folder like this:

```js
const pane = new Tweakpane();
const params = {
  foo: 123,
  bar: 'hi',
}

const f = pane.addFolder({
  title: 'folder',
});
f.addInput(params, 'foo');
f.addInput(params, 'bar');
f.addButton({
  title: 'baz',
})

// You can exnapd/collapse a folder by .expanded
f.expanded = false;
```
```

**Comment by ciknowles** [comment]
Hi,

Thanks for you reply! I tried this but doesn't really fit my interface. I'll try and explain with an example.

I want a drop down input component. The user can select say 'Rectangle', 'Square', 'Circle' + a number of other shapes. When the user selects a shape I want the properties for this particular shape to show beneath. I have a lot of different items and I don't want a folder for each (unless I can hide it).

I can 'hack it in' by accessing item.controller.view.ele_.style  (or something liek this) but this seems a little clumsy.

Chris

Chris

**Comment by cocopon** [comment]
I understand the situation! Added `hidden` property to toggle visibility. Please wait for the next release.

**Comment by ciknowles** [comment]
Wow - thank you!
