### ISSUE TITLE
Style Specificity 

### ISSUE THREAD

**Issue by ciknowles** [cocopon/tweakpane#58]
Hi,

I have been trying to incorporate Tweakpane into a site. I am having difficultly with styling. In particular, the site I'm working with has existing styles that use selectors such as 

button:not(.toggle) 

This sets the background colour and button padding amongst other things. This overrides the Tweakpane styling (as far as I can tell) because this selector has a higher css 'weight' or specificity.

Have you got any suggestions for how I can get around this?

Thanks,

Chris

**Comment by ciknowles** [comment]
I've investigated this some more. 

Any existing styles, such as input[type='text'] will take preference over the class styles that are defined in tweakpane as they have higher specificity. However, tweakpane is tweakpane because it looks good.

Looking at the css specificity rules I can see a few solutions. One would be to add a .tweakpane css class to the tweakpane main div and then make your rules .tweakpane .tp-rotv_t etc,etc. As there would now be 2x class selectors this would take preference over rules such as input[type="...

I'm no expert in this, there are probably better solutions...

**Comment by ciknowles** [comment]
Ok, this is no long term solution but here is a dodgy hack. 

I added a 'tweakpane' class to my tweakpane div. 

Then dynamically tweaked the tweakpane style using javascript.

 	var tpstyle = document.querySelector("style[data-for='tweakpane']");
	tpstyle.innerHTML =	tpstyle.innerHTML.replace(/.tp-fldv_t,.tp-rotv_t/g, '.tweakpane .tp-fldv_t,.tweakpane .tp-rotv_t'); 
	tpstyle.innerHTML = tpstyle.innerHTML.replace(/}.tp-/g, '}.tweakpane .tp-');

**Comment by cocopon** [comment]
I think it is a responsibility of a website. We can add a workaround in the case of your example, but if a website has higher specificity definitions, we have to append another class name or consider to use `!important`. It will be endless...

**Comment by ciknowles** [comment]
Hi,

!important isn't any good. I agree.

It was the input[type='... that caused me the most problems. My hack above worked. Seems a little heavyweight to update the style at runtime. All I'm doing is effectively namespacing it.

Are there any other nicer solutions that I've missed?

Chris

**Comment by cocopon** [comment]
Your solution looks good for this case. Or, you can change a style of a site like this:

```html
<form class="someForm">
  <input class="someForm_textInput">
</form>
```

```css
.someForm_textInput {
  ...
}
```

This is a CSS design methodology called [BEM](http://getbem.com/introduction/) to avoid such annoying problem about CSS specificity.

**Comment by ciknowles** [comment]
Hi,

I'm actually embedding some 3D stuff (using Tweakpane) into a Wordpress site. I obviously don't have control over the Wordpress styles so I need to 'fix' my UI within my code. I can't change the Wordpress css, there is just too much of it.

I always find that gluing lots of things together is where I have problems.

Chris

**Comment by cocopon** [comment]
That's tough...

I came up with another idea. Tweakpane doesn't inject a style if `style[data-for=tweakpane]` already exists. So you can inject a modified (pre-replaced) style before creating a pane.

**Comment by ciknowles** [comment]
Hi,

That's a good idea. I'll investigate that. 

Thank you!
