### ISSUE TITLE
color panel is displaying incorrectly

### ISSUE THREAD

**Issue by Hanysisko** [cocopon/tweakpane#580]
In my project panel is displaying incorrectly. When I try to 'drag' color that I want, I need to drag cursor above color field or it will give only white or black color. Anyone had similar issue?
<img width="254" alt="image" src="https://github.com/cocopon/tweakpane/assets/77213663/3b81ed7a-8367-4724-bced-41003d135a27">

**Comment by cocopon** [comment]
It seems that it comes from your CSS. Can you share a minimum code to reproduce the issue? (e.g. using [CodeSandbox](https://codesandbox.io/))

**Comment by Hanysisko** [comment]
Hi cocopon, I just found it! The problem is that canvas for color palette takes property "position: fixed" from my main css file.
I have a question - is there a possibility for fixing this WITHOUT changing my main css file f.e. changing it somewhere in file where I'm using Pane() ?

**Comment by cocopon** [comment]
Ideally you should fix your CSS because this problem comes from a scope that is too wide. However, if you can't do it in some reason, overwriting it with a more specific declaration can be a workaround.

```css
/* If you can add a ruleset to the existing CSS... (NOT RECOMMENDED) */
.tp-rotv canvas {
  position: static !important;
}
```

```js
// If you can't modify your CSS in some reason... (NOT RECOMMENDED)
pane.element.querySelectorAll('canvas').forEach((c) => {
  c.style.position = 'static';
});
```
