### ISSUE TITLE
Bug with Tab when we have controls after the Tab

### ISSUE THREAD

**Issue by kasra0** [cocopon/tweakpane#581]
Hi,

Version : 4.0.1

These Two screenshots show the problem.

<img width="270" alt="tabA-selected" src="https://github.com/cocopon/tweakpane/assets/16036382/4b32f514-edcd-460d-986d-dd2f28359dd2">
<img width="270" alt="tabB-selected" src="https://github.com/cocopon/tweakpane/assets/16036382/f390fb9e-b75b-418e-a04f-f341e73cc2da">

For some reason the controls after are duplicated.
This happens specifically when the length of the tabs is not the same.

```
import React, { useState, useEffect } from 'react';
import { Pane } from 'tweakpane';
export const BugTab: React.FC = () => {
  const [width, setWidth]  = useState<number>(200);
  const [height,setHeight] = useState<number>(200);
  useEffect(() => {
    const pane  = new Pane();
    const param = {width,height };
    const tab   = pane.addTab({
        pages: [{title: 'A'},{title: 'B'}, ],
      });
     const firstTab  =  tab.pages[0]
     const secondTab =  tab.pages[1]
     firstTab.addBinding(param, 'width', {min: 0,max: 400}).on('change', (e)=>setWidth(e.value))
     firstTab.addBinding(param, 'height',{min: 0,max: 400}).on('change', (e)=>setHeight(e.value))
     secondTab.addBinding(param,'width', {min: 0,max: 400}).on('change', (e)=>setWidth(e.value))
     pane.addBinding(param,     'width', {min: 0,max: 100}).on('change', (e)=>setWidth(e.value))
}, []);
  return null
};
export default BugTab;
```

Maybe I have to destroy a previous state I don't know...
Am I missing something  or it's a bug ?
Thanks

**Comment by cocopon** [comment]
It seems that this is not a bug of Tweakpane. Can you see a drop shadow between the second `width` field and the third `width` field? This indicates that multiple panes are created and overwrapped at the same place.

![image](https://github.com/cocopon/tweakpane/assets/602961/b1b145d0-3e23-4b5b-9f3f-54c949eaa5a3)

**Comment by cocopon** [comment]
Feel free to reopen the issue if you have any updates.
