### ISSUE TITLE
[feature request] tabs: vertical layout

### ISSUE THREAD

**Issue by eviltik** [cocopon/tweakpane#595]
Hi again

This is blender
![image](https://github.com/cocopon/tweakpane/assets/4477890/3278e248-f404-4428-8a15-fdd4f22a8561)

As you can see, we have vertical tabs with icon (and/or vertical text ?)

It should be great to be able to make the same layout with tweakpane :)

For icons, see #594

**Comment by cocopon** [comment]
Hi! I think this kind of view should be handled by the plugin system. It's possible to create a plugin that provides a container component like a folder and a tab.

**Comment by eviltik** [comment]
It should be great to have it by default in tweakpane rather than a plugin, but it's my point of view.

Wondering if it can not be solve just with specific css.

I'll try to go deeper for a plugin (but i'm limited, i stay sticked with vanilliajs for years, and it seem's that plugins are typescript)

**Comment by cocopon** [comment]
> It should be great to have it by default in tweakpane rather than a plugin

Built-in Tweakpane components are arranged in stacked rows. Tweakpane calls them as "blade", and the vertical tab seems different from this setup. 

<img width="871" alt="image" src="https://github.com/cocopon/tweakpane/assets/602961/b67c7bb1-6c0b-4ecc-820a-1b555d461587">
https://tweakpane.github.io/docs/quick-tour/#blades

I think this kind of complex components should not be included in the standard components.

> Wondering if it can not be solve just with specific css.

It seems difficult based on my experience. (e.g. height calculation, layout with text tab, etc...)

**Comment by eviltik** [comment]
I see, thank you !
