### ISSUE TITLE
Please add a UMD library version again.

### ISSUE THREAD

**Issue by create3000** [cocopon/tweakpane#599]
I am using Electron, and libraries can only be imported view `require`. Version 3.* of Tweakpane was still available as UMD, thank you guys. With some small changes, `package.json` could handle this:

```json
{
	"main": "dist/tweakpane.js",
	"module": "dist/tweakpane.mjs",
	"exports": {
		".": {
			"require": "./dist/tweakpane.js",
			"import": "./dist/tweakpane.mjs"
		}
	},
}
```

This is a minimal example how it could be. Please be careful with the path names, dots and slashes are important, names and suffixes can be choosen as you like. It should then be possible to use Tweakpane with both ESM `import` statement and Node `require`.

**Comment by cocopon** [comment]
I've decided to distribute v4 exclusively as ES modules for better maintainability. If you need UMD support, you can continue to use v3.

**Comment by create3000** [comment]
I actually assumed that you could automate the whole thing with a build script and that this would not result in any additional work for you.

**Comment by cocopon** [comment]
There are many ways to use the package: through npm, package bundlers, tsc, or directly using a file, etc. For example, package.json have a property "type: module", indicating that this package exclusively supports ES modules, and does your suggestion still work under these conditions? I'll need to verify all compatibilities for each method by writing test cases, ensuring support across future updates.

**Comment by aayushchouhan24** [comment]
sir please add UMD version i want to use your library  in my library  

But my library  is  for both UMD AND ES 

So i would need to manually modify and host the CDN

Plz help!!!


my modification's

(function (global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
        typeof define === 'function' && define.amd ? define(['exports'], factory) :
            (global = typeof globalThis !== 'undefined' ? globalThis : global || self, factory(global.tweakpane = {}))
})(this, (function (exports) {
    'use strict'


//rest of your library  while replacing "export { BladeApi, ButtonApi, FolderApi, ListBladeApi, ListInputBindingApi, Pane, Semver, SeparatorBladeApi, SliderBladeApi, SliderInputBindingApi, TabApi, TabPageApi, TextBladeApi, TpChangeEvent, VERSION };"



    exports.BladeApi = BladeApi
    exports.ButtonApi = ButtonApi
    exports.FolderApi = FolderApi
    exports.ListBladeApi = ListBladeApi
    exports.ListInputBindingApi = ListInputBindingApi
    exports.Pane = Pane
    exports.Semver = Semver
    exports.SeparatorBladeApi = SeparatorBladeApi
    exports.SliderBladeApi = SliderBladeApi
    exports.SliderInputBindingApi = SliderInputBindingApi
    exports.TabApi = TabApi
    exports.TabPageApi = TabPageApi
    exports.TextBladeApi = TextBladeApi
    exports.TpChangeEvent = TpChangeEvent
    exports.VERSION = VERSION

}))

**Comment by cocopon** [comment]
Here is my opinion at this time.
https://github.com/cocopon/tweakpane/issues/599#issuecomment-1923456585

**Comment by ffd8** [comment]
Quick belated chime on this topic. I hoped to share this library with my students (mainly using p5.js for creating visual tools) – so a UMD export is oh so useful when experimenting with toggling a few libraries and testing the waters with plain HTML/CSS/JS. I'll share v3 with them. Thanks for considering re-implementing and seeing if it could be an automated part of the build process.
