### ISSUE TITLE
export folder -> import folder not working as expected

### ISSUE THREAD

**Issue by autonome** [cocopon/tweakpane#600]
Here is example code for creating a new basic pane, with a folder and a binding, and exporting the folder state.

Then it adds a new folder, and imports the folder state.

The second folder should now look exactly like the first.

However, the binding is missing.

```
const pane = new Pane({
  container: el,
  title: labels.containerTitle
});

const f = pane.addFolder(
  {title: 'test folder'}
);

const strBinding = f.addBinding(
  {foo:'bar'},
  'foo', {}
);

const str = JSON.stringify(f.exportState(), null, ' ');

console.log(str);

const f2 = pane.addFolder(
  {title: 'test folder 2'}
);  

f2.importState(state);
```

**Comment by autonome** [comment]
Hm, if i make a new Pane and import the same state directly to the pane, neither the folder or binding is created.

**Comment by cocopon** [comment]
`importState` and `exportState` are literally for importing/exporting a pane state. They don't create new controls even if the state contains missing properties. If you want to import the value, you have to create a binding with the same name before importing.

**Comment by autonome** [comment]
Aha, in that case this issue can certainly be closed.
