### ISSUE TITLE
Ability to manually select the binding view type

### ISSUE THREAD

**Issue by Sija** [cocopon/tweakpane#602]
ATM it seems it's not possible to override the `view` selected for the values passed to the `Pane.addBinding` function. In some cases the heuristics behind the automatic view selection (which are based on the value type and content), are not working as expected, and such ability would provide an escape-hatch, or just a more stable behaviour.

Refs #601

**Comment by cocopon** [comment]
#601 should be fixed, and you can use `view: 'text'` for disabling color detection:

https://tweakpane.github.io/docs/input-bindings/#color

<img width="957" alt="image" src="https://github.com/cocopon/tweakpane/assets/602961/e61f2a0e-dd6e-4111-9ea8-73c3477c426b">

**Comment by Sija** [comment]
I tried but it doesn't work for lists.

**Comment by cocopon** [comment]
Hm, can you share the code and the Tweakpane version? It works fine on the document with the latest Tweakpane.

<img width="725" alt="image" src="https://github.com/cocopon/tweakpane/assets/602961/da81bf53-82bb-4436-8838-a7880d56dc8d">

https://tweakpane.github.io/docs/

```js
p = new Tweakpane.Pane();

// without view: 'text'
p.addBinding(
  {foo: '#f00'}, 'foo',
  {
    options: {red: '#f00', blue: '#00f'},
  }
) 

// with view: 'text'
p.addBinding(
  {foo: '#f00'}, 'foo',
  {
    view: 'text',
  }
) 

// with options and view: 'text'
p.addBinding(
  {foo: '#f00'}, 'foo',
  {
    options: {red: '#f00', blue: '#00f'},
    view: 'text',
  }
) 
```

**Comment by Sija** [comment]
I was setting `view: "list"` with `view: "text"` it works correctly, thanks!
