### ISSUE TITLE
Receiving NaN values while disposing

### ISSUE THREAD

**Issue by titouan-pellerin** [cocopon/tweakpane#609]
Executing the `dispose` method of a binding while dragging it, triggers an update with a NaN value (while dealing with number). This behavior is not excepted, and is causing me some problems.

`this.pane?.dispose();`

**Comment by cocopon** [comment]
This is an unexpected usage. Disposing of a binding while dragging it means that the binding will be removed during the dragging process. I think this is strange behavior for users.

**Comment by cocopon** [comment]
Feel free to reopen the issue if you have any updates.
