### ISSUE TITLE
Question about multiple objects and arrays

### ISSUE THREAD

**Issue by 2mik** [cocopon/tweakpane#610]
Hi,

Please clarify if the following features are currently exist or not:

1. Is it possible to display properties of multiple selected objects to change their properties by a single user action? For example, a user selects Button1 and Button2 to set their properties to the same values. If this feature not supported out of the box, may be you can share an idea how to implement it?
2. Is it possible to add a binding to edit an array?

Thank you.

**Comment by cocopon** [comment]
Hi,

1. There is no smart way to achieve that. For example:
   ```js
   function applyObj1PropsToObj2() {
     obj2.foo = obj1.foo;
     ...
   }
   
   pane.addBinding(obj1, 'foo').on('change', () => {
     applyObj1PropsToObj2();
   });
   
   ...
   ```

2. No, you should bind each single item if it is an object, or [create a new plugin](https://tweakpane.github.io/docs/plugins/dev/) for arrays.

**Comment by 2mik** [comment]
Thanks.
