### ISSUE TITLE
Palette view (Feature request)

### ISSUE THREAD

**Issue by lazarusA** [cocopon/tweakpane#611]
A lot of use cases in science, displaying objects that follow a given colormap is a common practice. Hence, having an up to date feature like this could be a nice addition. 

Maybe integrating: https://github.com/brunoimbrizi/tweakpane-plugin-chromatic (which is outdated)

could be a good point to start. 

best,
L

**Comment by cocopon** [comment]
I don't have a plan to add a complex control like that to the Tweakpane core. You can send a pull request to the plugin, support its development with sponsorship, or fork it yourself.
