### ISSUE TITLE
Add order to base params

### ISSUE THREAD

**Issue by alexandernanberg** [cocopon/tweakpane#614]
Using index to order the blades isn't intuitive imo. When dynamically adding blades I don't often know what index I want to insert a specific item to.

I almost always want to set an arbitrary number, e.g. `order: 100` if I likely always want that blade at the bottom. But if there is an exception I can set the order of another item to `101` etc.

AFAICT there is no nice way to achieve that with `index.`.

**Comment by cocopon** [comment]
Thank you for sharing your opinion, but currently I don't plan to add such a parameter.

One of Tweakpane's core principles is simplicity. Using `index` is the simplest way to organize ordered items.

I believe that more complex features like this should be managed by users.

**Comment by cocopon** [comment]
Feel free to reopen the issue if you have any updates.
