### ISSUE TITLE
How to clear blades?

### ISSUE THREAD

**Issue by 2mik** [cocopon/tweakpane#616]
Hello,

Thank you for your work. Probably, my question is simple. However, I can't find answer in the docs and issues.

In case we have edited a one object using Tweakpane, and need to edit properties of another object. How do we properly clear a Pane before adding new bindings?

**Comment by cocopon** [comment]
Thank you for using Tweakpane.

You need to dispose of the existing blade and then create a new blade with a new binding.
https://tweakpane.github.io/docs/misc/#disposing

**Comment by 2mik** [comment]
Thank you.
