### ISSUE TITLE
Drag-rearrange folders inside a pane

### ISSUE THREAD

**Issue by aniongithub** [cocopon/tweakpane#618]
How can I extend tweakpane to allow drag-rearranging of folders inside the same pane? Is this even possible?

Thanks!

**Comment by cocopon** [comment]
There isn't an easy way to achieve this, but you could try something like the following:

- Add mouse event listeners to the folder [element](https://tweakpane.github.io/docs/api/classes/FolderApi.html#element)
- [Remove](https://tweakpane.github.io/docs/api/classes/FolderApi.html#remove) the folder
- Re-[add](https://tweakpane.github.io/docs/api/classes/FolderApi.html#add) the folder to the specified position using the `opt_index` option

**Comment by aniongithub** [comment]
Thanks, I'll give this a shot an report back here,

**Comment by aniongithub** [comment]
I ended up using move up/down buttons in each folder, the visual aspect of the dragging would have been very complicated. Thanks for the pointers!
