### ISSUE TITLE
Example for options text (i18n)

### ISSUE THREAD

**Issue by ciknowles** [cocopon/tweakpane#62]
Very minor!

I couldn't find anything in the documentation about localizing tweakmenu text - particularly in selections. After digging around the code and I bit of trial and error I found you could like this!

tweakpane.addInput(menu, 'value', {label:'Shape'
						,options: [
							{value: 'rectangle', text: 'Rectangle'}
							,{value: 'circle',	text: 'Circle'}
						]			
					});

Chris

**Comment by cocopon** [comment]
Yes. `options: {key1: value1, key2: value2, ...}` works fine in most cases so I added only this format. You can find another format in API reference: https://cocopon.github.io/tweakpane/api/interfaces/numberinputparams.html#options
