### ISSUE TITLE
Parameter to change the width of the pane

### ISSUE THREAD

**Issue by d3ttl4ff** [cocopon/tweakpane#622]
Hi!

It would be very convenient to have a parameter to change the width of the pane. Most of the time the width is perfectly fine for the label names. But when I use long label names, it gets messy.

I have seen that we can do it manually by changing the main file or setting a custom container. But with all the other awesome features tweakapane has, this will also be a really nice feature to have. I'd love to change the width using a parameter as I go.

**Comment by cocopon** [comment]
Hi,

Please refer to the older issue here: https://github.com/cocopon/tweakpane/issues/46#issuecomment-633388907

**Comment by d3ttl4ff** [comment]
Oh thank you! I have seen it. I just thought of having a parameter to change it. But, this way works fine as any. 

Thanks again!
