### ISSUE TITLE
Events other than `change` for text blades?

### ISSUE THREAD

**Issue by Bug-Reaper** [cocopon/tweakpane#625]
I'm seeing this:
<img width="316" alt="Screenshot 2024-09-23 at 1 22 22 AM" src="https://github.com/user-attachments/assets/938591ce-608f-4a27-9cc8-bfa2bd4ec3b4">
However none of those seem to emit? no combo of the following works:
```js
// Works fine
blade.on('change',()=>{/*...*/})

// None of the following work
blade.on("keyup",(ev)=>{/*...*/})
blade.on("keydown",(ev)=>{/*...*/})
blade.on("input",(ev)=>{/*...*/})
blade.on("inputChange",(ev)=>{/*...*/})
```

**Comment by cocopon** [comment]
Text blade only supports `change`.
https://tweakpane.github.io/docs/api/classes/TextBladeApi.html#on

You can handle those events directly via `.element`:

```js
const elem = blade.element.querySelector('input');
elem.addEventListener('keyup', () => {
  // ...
});
```

**Comment by cocopon** [comment]
Feel free to reopen the issue if you have any updates.
