### ISSUE TITLE
Curate the topics page

### ISSUE THREAD

**Issue by tallneil** [cocopon/tweakpane#627]
Current topics page is unclaimed / uncurated: 
https://github.com/topics/tweakpane

How to curate: 
https://github.com/github/explore/blob/main/CONTRIBUTING.md#curating-a-new-topic-or-collection

**Comment by cocopon** [comment]
Interesting, but I don't have the bandwidth to keep track of updates for all third-party plugins. It would be great if the community could handle this.

**Comment by tallneil** [comment]
PR: https://github.com/github/explore/pull/4473

**Comment by tallneil** [comment]
Topics page is now claimed / curated: 
https://github.com/topics/tweakpane

**Comment by cocopon** [comment]
Great work! Thank you for your help.
