### ISSUE TITLE
Ability to change min/max/step etc at Runtime

### ISSUE THREAD

**Issue by ciknowles** [cocopon/tweakpane#63]
Hi,

I'm confused by this one. I don't know how to update any config of the config parameters at runtime.

For example:

Create a point 2D menu
config = {label:'Center',x: {min: -100, max: 100, step:0.1 },y: {min: -100, max: 100, step:0.1 }};
tweakpane.addInput(menu, 'value', config);

If I then change config sometime later (because the user has changed a container size for example)
config.x.min = -10
tweakpane.refresh();

The min/max values are not updated. Not sure how to even hack this one?

Chris

**Comment by cocopon** [comment]
Currently there is no way to change parameters at runtime for maintainability reason. Please dispose a component and re-create it with new options.

**Comment by ciknowles** [comment]
Hi,

This might work but how do I dispose a component (say an input) and then recreate it in the same place?

Thanks,

Chris

**Comment by cocopon** [comment]
Ah I forgot to add `dispose()` to input binding API. I just released the latest version 1.3.5 so please check it.

**Comment by ciknowles** [comment]
Ah,

I see that. So calling .dispose on the input binding will remove the item.

My next difficult question is - can I then re-add a new input *in the same place* that I've just removed one?

I've taken a look at the codebase - I see the problem with updating the config at runtime . Views are created in the view constructor with a div which is then appended. Unfortunately, I don't code ts so I'm struggling to work out how to allow the view to be recreated in the same place if the config is changed.

Chris

**Comment by cocopon** [comment]
You can use `index` config to specify a position of input. https://cocopon.github.io/tweakpane/misc.html

**Comment by cocopon** [comment]
Here is a simple example for re-creating a component with new config: https://codepen.io/cocopon/pen/pogJVQp

**Comment by ciknowles** [comment]
AH,

Missed that. Fabulous. 

FYI, I am asking about the config because I'm controlling a 3D scene where you can put sub objects on the face of an existing object. 

Obviously, if you choose a different face, then the boundary of where you can place the sub object will change. Hence my questions!

Chris

**Comment by cocopon** [comment]
I understand! Thank you for the detailed information.

**Comment by ciknowles** [comment]
Hi,
I'm now using 1.3.5. 

Hidden works really well - thanks.
Dispose and then recreate also works - thanks! It's a little tricky (well not that tricky) as you need to maintain a reference to the InputBinding interface and also the index when you first add. 

Many thanks.

Chris

**Comment by cocopon** [comment]
Please refer `InputParams` section. You can see `index` option in each type.
https://cocopon.github.io/tweakpane/api/index.html#inputparams
