### ISSUE TITLE
typescript  `addBlade` interface does not expose `on` method

### ISSUE THREAD

**Issue by xiduzo** [cocopon/tweakpane#633]
![image](https://github.com/user-attachments/assets/efed4276-7230-4692-ba5f-61b25770617f)

```
const pane = new Pane()

pane
  .addBlade(...)
  .on('change') // does not exist on interface, functionality works fine
```

the type bring me to `node_modules/core/dist/blade/common/api/blade.d.ts` which I assume gets generated from https://github.com/cocopon/tweakpane/blob/main/packages/core/src/blade/common/api/blade.ts

**Comment by cocopon** [comment]
Not of all blades have `.on()`. See the Blades section:

> If you are a TypeScript user, need to cast a created blade to a specific type to access full functionalities:
https://tweakpane.github.io/docs/blades/

**Comment by xiduzo** [comment]
Thanks, I missed that from the docs. My bad.

But can't this be inferred by the `view` of the blade itself?

**Comment by cocopon** [comment]
> But can't this be inferred by the view of the blade itself?

It's difficult because `.addBlade()` can be extended by adding plugins.
