### ISSUE TITLE
Point 2D - y inverted?

### ISSUE THREAD

**Issue by ciknowles** [cocopon/tweakpane#67]
I've noticed on the Point 2D input when you expand the pad that the y appears to be inverted. Not sure if this is intended?

I would expect the upper right quadrant of the pad to be +v.e for both x and y. 

I tried reversing my min and max (and step) but this doesn't work. 

I've attached an image
![tweakpane_1](https://user-images.githubusercontent.com/16463779/83974854-31d2d080-a8e8-11ea-8ba6-f2d6fd6bbba7.png)

Chris

**Comment by cocopon** [comment]
This is by design, natural in computer coordinate system. `min` means minimum, `max` means maximum, so you should not reverse them.

**Comment by cocopon** [comment]
On second thought, inverted Y axis is more user-friendly so I'll add an option like `invertsY` to Point2D input later.

**Comment by ciknowles** [comment]
Super - thank you!

**Comment by cocopon** [comment]
Added `inverted` option to Y-axis in 49552bd. Please wait for the next release.

```js
const PARAMS = {
  offset: {x: 50, y: 50},
};

const pane = new Tweakpane();
pane.addInput(PARAMS, 'offset', {
  y: {inverted: true},
});
```
