### ISSUE TITLE
onTitleClick_ implementation

### ISSUE THREAD

**Issue by abolfazlshirazi** [cocopon/tweakpane#74]
Hi again,

Is there any way to properly add an event listener to the folder title when the user expand or collapse? Something like the followings when creating a new folder:

`
  myFolder= myPanel.addFolder({ title: 'Some title!' }).on('click', (thisFolder) => { console.log("The title of thisFolder is clicked"); }) ;
`

I know that there is a "onTitleClick_" event for the folder titles that is used internally in the code. But I do not know how to modify it properly. I tried the followings, which did not work:

`myFolder.controller.onTitleClick_ = function() { FLDR_SP.controller.onTitleClick_() ; myFcn(); }`

However, the following hack does the trick:

`myFolder.controller.view.element.addEventListener("click",myFcn)`

Is there a better an cleaner way to do this? somehow taking advantage of onTitleClick_ ?

**Comment by cocopon** [comment]
It's undocumented but you can handle `fold` event of a folder.

```js
const pane = new Tweakpane();
pane.addFolder({title: 'Folder'}).on('fold', (expanded) => {
  console.log(expanded);
});
```

**Comment by abolfazlshirazi** [comment]
Thanks. I just tried it and it works.
However, "expanded" is undefined, which is the function input argument. But that's Ok.

**Comment by cocopon** [comment]
What version of Tweakpane do you use? If you are using older version, please try the latest one.

**Comment by cocopon** [comment]
Closed. Reopen the issue if you still have the problem.
