### ISSUE TITLE
Point 2D - key support

### ISSUE THREAD

**Issue by ciknowles** [cocopon/tweakpane#75]
Hi,

I'm using the Point 2D input to position an object. If you click in either the X or Y fields this allows the up/down arrows to be used to change the values - great.

If I expand the 2D pad, I can only change the position by clicking on the pad. It would be great if I could use the arrow keys to move the position on the pad.

Would this be possible? 

If not, is there any way to bind to a keypress event for a particular item on Tweakpane so that I could do this myself?

Thanks,

Chris

**Comment by cocopon** [comment]
Thank you for your feedback. Implemented in ce483ac so please wait for the next release.

**Comment by cocopon** [comment]
Released! Try the latest version 1.5.2.
