### ISSUE TITLE
Plugin system

### ISSUE THREAD

**Issue by cocopon** [cocopon/tweakpane#78]
Related: #17, #42

**Comment by pspeter3** [comment]
A plugin structure would allow a file input as well which would be nice.

**Comment by pavelvasev** [comment]
I would be happy with some method of adding just my own DOM at runtime, instead of text input. Is that possible now?

**Comment by marquizzo** [comment]
Could you elaborate on how this plugin system would work? Does that mean people could eventually write and collaborate with their own custom controls?

**Comment by pspeter3** [comment]
Yeah, I think the ability to add new controls would be great.

**Comment by cocopon** [comment]
> Does that mean people could eventually write and collaborate with their own custom controls?
Yes. I plan to rewrite all inputs/monitors by new plugin structure. It means that you can do the same things as existing controls.

**Comment by cocopon** [comment]
Released the latest version 2.0.0 and the plugin system is now in public beta! Please try it and give your feedback.
