### ISSUE TITLE
Theming with CSS3 vars

### ISSUE THREAD

**Issue by meodai** [cocopon/tweakpane#8]
Great project! I Would you be open to receive a pull request for an idea I had, to use CSS3 vars to theme tweakpane? I often want to adapt the panes in by projects.

**Comment by cocopon** [comment]
Before implementing the feature, I think we need to categorize component parts, organize them, and figure out a minimum required color palette.

I also think it would be great if users can create a color theme or apply the existing ones (e.g. Solarized, Gruvbox, Monokai, Onedark, Iceberg, ... etc.) to the pane easily.

Based on these, I made a proposal of themable color palette:


- Base background
  - Pane
  - Picker
	  - Color
		- Point2D

- Folder foreground
  - Folder title
  - Folder screw

- Folder background (active, focus, hover)

- Field label

- Input view foreground
  - Text input
  - Checkbox mark
	- Point2D

- Input view guide foreround
  - Point2D axis

- Input view background (active, focus, hover)
  - Text input
  - Checkbox box
	- Point2D pad
  - Slider track

- Monitor view foreground
  - Monitor
	  - Text
		- Graph

- Monitor area background
  - Monitor
	  - Text
		- Graph

- Button-like control background (active, focus, hover)
  - Button
  - Slider knob
	- List

- Button-like control foreground (active, focus, hover)
  - Button title
	- List title
	- List arrow

- Separator


--


- `$color-base-bg`
- `$color-folder-fg`
- `$color-folder-bg`
- `$color-folder-bg-active`
- `$color-folder-bg-focus`
- `$color-folder-bg-hover`
- `$color-input-bg`
- `$color-input-bg-active`
- `$color-input-bg-focus`
- `$color-input-bg-hover`
- `$color-input-fg`
- `$color-input-guide-fg`
- `$color-monitor-fg`
- `$color-monitor-bg`
- `$color-button-bg`
- `$color-button-bg-active`
- `$color-button-bg-focus`
- `$color-button-bg-hover`
- `$color-separator`

**Comment by cocopon** [comment]
Released in 1.3.0.

**Comment by seamanmur** [comment]
Is it possible to make one of the labels a different color? For example - in red to emphasize that the data here is incorrect. I didn't find that...

**Comment by rishipandey125** [comment]
I am wondering the same thing as above

**Comment by cocopon** [comment]
Added `element` property to blades in #392 and you'll be able to modify elements from the next version.
