### ISSUE TITLE
Disabled input

### ISSUE THREAD

**Issue by vujadin** [cocopon/tweakpane#84]
Is it possible to disable text or number input? 
It would be very useful to create read-only fields, and to enable/disable them as needed.
Maybe via InputParamsOption with optional "enabled" flag?

**Comment by cocopon** [comment]
You can use `addMonitor` to add read-only fields. https://cocopon.github.io/tweakpane/monitor.html

**Comment by vujadin** [comment]
That will work. Thanks!
