### ISSUE TITLE
How to update options of String list?

### ISSUE THREAD

**Issue by vujadin** [cocopon/tweakpane#85]
Is it possible to update options of a string list component (to have more or less items in a drop-down list) ?

**Comment by cocopon** [comment]
You can do it by disposing the input and then re-creating it with new options.
(Related: #63)

**Comment by vujadin** [comment]
It would be great if we could just update options of an existing one. Right now I'm using tweakpane in electron app to expose all properties of PIXI.Text object and there are a lot of them, so I need to rebuild whole pane content every time user selects some PIXI.Text object... Disposing and recreating only one component breaks the original order and puts new component at the bottom.

**Comment by vujadin** [comment]
Just read full #63
