### ISSUE TITLE
MIDI Support

### ISSUE THREAD

**Issue by cmalven** [cocopon/tweakpane#87]
Hello! This project is amazing. As a dat.gui superfan I'm very surprised I haven't stumbled across this before.

I maintain a library for personal use - https://www.npmjs.com/package/@malven/gui - that is essentially just an abstraction on top of dat.gui that mostly just provides effortless, near automatic support for MIDI controllers. I use a MIDI knob controller that I find makes it way more intuitive, interactive, and fun to tweak parameter values.

I'd love to experiment with doing something similar for tweakpane, but I'd ideally like to avoid going down the route of creating another abstraction on top of tweakpane and instead build a more "official" connection.

I see you have official plugin support on the roadmap, but I'd totally understand if that's months/years away from being a priority for you.

Short of an official plugin, do you have any recommendations for how you would go about this? Not looking for specific implementation details or anything, just a high level nudge in the right direction. Thanks!

**Comment by cocopon** [comment]
Thank you!

> do you have any recommendations for how you would go about this?

Currently my plan of a plug-in system #78 is for providing custom UI components for parameter values. For example:

- Dial input for number values
- Calendar input for date values
- ...

So I think this feature doesn't affect to your project.

**Comment by cocopon** [comment]
Closed because it seems to be resolved.
