### ISSUE TITLE
Moveable/Floating Panes

### ISSUE THREAD

**Issue by tscritch** [cocopon/tweakpane#88]
Hey I've been looking for something like this! Great work! 

I had a question/possible enhancement. With IMGUI you can move the panes around freely and dock them. Do you have the ability to move the panes around right now? If not I would love to help add that!

**Comment by cocopon** [comment]
Thank you!

Tweakpane has an option `container` to specify its parent element and users can locate the pane to anywhere with that option. So I think a position of the pane is out of scope of the library.

**Comment by tscritch** [comment]
Ok no worries! That makes sense. Thanks for the response!
