### ISSUE TITLE
should config include expanded option

### ISSUE THREAD

**Issue by spayton** [cocopon/tweakpane#92]
Hi,

Just playing with TweakPane, really like it.  I can see that folders have an 'expanded' property which can be set on construction but the main pane doesn't.  Although I can set the pane expansion programatically afterwards, it would seem logical to also offer this during construction, in the config object, like folders.  Also the hidden property would also be suited to be available in the config.

Just an idea!

**Comment by cocopon** [comment]
> I can see that folders have an 'expanded' property which can be set on construction but the main pane doesn't

Right. I added the option in #94. Please wait for the next release.
