### ISSUE TITLE
How to use tweakpane

### ISSUE THREAD

**Issue by Kaperskyguru** [cocopon/tweakpane#93]
I want to write an article about this on LogRocket blog, How do I use it. I followed the get started page.
1. Added a Script tag to my html file.
2. Created a new `new TweakPane()`  
3. Added some configurations as specified in the Page

After all this, I preview the HTML file and nothing displayed. Please how do i use this TweakPane library?

**Comment by cocopon** [comment]
First, please fix a typo: `new TweakPane()` -> `new Tweakpane()`

If the problem still occurred,

1. What is a browser do you use?
2. You can use a developer tool of a browser to find a cause. Is there any logs or error messages in a console?

**Comment by cocopon** [comment]
Problem solved? What is the cause?

**Comment by Kaperskyguru** [comment]
My fault, I had a typo
