### ISSUE TITLE
Only update Monitor on demand - feature request

### ISSUE THREAD

**Issue by spayton** [cocopon/tweakpane#96]
Hi,  I like the monitor control but I am finding that important data is either being missed due to sampling rate or it's scrolled off.  What would help and provide additional functionality would be a way to change the sampling mode from auto to on-demand.

Maybe there is an official way I didn't notice, but have found I can do this in a hacky way, as follows:

1. set interval to 0 in monitor config
2. add values eg, pm.controller.controller.value.append(0.1)

Would adding an append member function to the MonitorBindingApi, to allow official usage in this way be possible?

**Comment by cocopon** [comment]
I agree with you! Currently there is no official way to update a monitor manually, so I'll implement the feature later.

**Comment by cocopon** [comment]
Maybe... can you do it by using `refresh()` of the monitor? this method manually fetches a bound value.

```js
const pane = new Tweakpane();
const pm = pane.addMonitor(target, 'foo', {
  interval: 0,
});

pm.refresh();
```

**Comment by spayton** [comment]
Yes, that works.

Although having the ability to update with a supplied value is slightly more flexible than having to set the property value, which requires access to the base object.

**Comment by cocopon** [comment]
> having the ability to update with a supplied value is slightly more flexible than having to set the property value

I understand your use case, but `monitor` is for monitoring existing parameter values. Currently that is out of scope of Tweakpane.

**Comment by spayton** [comment]
Yes, of course.  I was using it as something which would be better described as a logger rather than a monitor.  I was also using it as monitor but adding in spike values to mark events in the trace.

**Comment by cocopon** [comment]
I know that there is a certain demand for general purpose UI library. If it was something like `addGraphView`, it would be natural to have a method for pushing a specific value. But at least for now, I don't have a plan to add such a method.

**Comment by cocopon** [comment]
So, in conclusion, if you'd like to update a monitor manually, change a bound value and run `update()`. Currently there is no plan to add a useful method for this case.
https://github.com/cocopon/tweakpane/issues/96#issuecomment-706505988

Feel free to reopen the issue if you still have a problem.
